// Episode 3 — "Human Dust"
// A game-original continuation: Hopo's institutions collapse while evidence becomes a wordless language.

import type {
  EndingDescriptor,
  EndingId,
  GameDefinition,
  Interaction,
  Item,
  Scene,
  SceneId,
} from "./types";

export const EP3_MAX_TURNS = 38;

export const EP3_ITEMS: Record<string, Item> = {
  FIRST_SHOT_REPORT: {
    id: "FIRST_SHOT_REPORT",
    name: "First-shot Causality Report",
    short: "Yang-bae's bullet struck Kali before the royal survivors turned on Hopo.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  EVAC_ROUTE: {
    id: "EVAC_ROUTE",
    name: "Civilian Safe Route",
    short: "Nak-yeon's named evacuation groups can cross Aydobor's deliberately open corridor.",
    art: "/images/game/ep2/items/search_map.svg",
    artifact: true,
  },
  TRAUMA_KIT: {
    id: "TRAUMA_KIT",
    name: "Sung-ae's Trauma Kit",
    short: "Enough supplies to stabilize one withdrawal line and document who can still move.",
    art: "/images/game/ep2/items/trauma_kit.svg",
  },
  CEASEFIRE_FLARE: {
    id: "CEASEFIRE_FLARE",
    name: "Last Ceasefire Flare",
    short: "One red signal remains. Every human muzzle must stay down while it burns.",
    art: "/images/game/ep2/items/ceasefire_flare.svg",
  },
  RIFLE_BOLTS: {
    id: "RIFLE_BOLTS",
    name: "Secured Rifle Bolts",
    short: "The removed actions of the hunters' rifles: visible proof that Hopo has disarmed.",
    art: "/images/game/ep2/items/hunting_ammo.svg",
  },
  CASUALTY_LEDGER: {
    id: "CASUALTY_LEDGER",
    name: "Casualty Ledger",
    short: "Names, wounds, blood types, and the order in which Hopo's living must move.",
    art: "/images/game/ep2/items/report.svg",
  },
  TRANSFER_ORDER: {
    id: "TRANSFER_ORDER",
    name: "Protected Transfer Order",
    short: "The health chief's protocol for moving Kali as a wounded child, not cargo or bait.",
    art: "/images/game/ep2/items/report.svg",
  },
  EVAC_MAP: {
    id: "EVAC_MAP",
    name: "Nak-yeon's Evacuation Map",
    short: "Cellars, alleys, and drainage paths known by the people who actually live in Hopo.",
    art: "/images/game/ep2/items/search_map.svg",
  },
  HAESUL_SKETCH: {
    id: "HAESUL_SKETCH",
    name: "Hae-sul's Movement Sketch",
    short: "A bodily witness account: the axe-bearer watches from the trees and leaves one corridor open.",
    art: "/images/game/ep2/items/search_map.svg",
  },
  CIVILIAN_MANIFEST: {
    id: "CIVILIAN_MANIFEST",
    name: "Civilian Evacuation Manifest",
    short: "Every resident assigned to a route, including the people the armed search forgot.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  KEROSENE_CAN: {
    id: "KEROSENE_CAN",
    name: "Kerosene Evidence Can",
    short: "Fuel taken from Yang-bae's shed. It could destroy the cold room and everything it proves.",
    art: "/images/game/ep2/items/workshop_clue.svg",
    losable: true,
  },
  KALI_STATUS_RECORD: {
    id: "KALI_STATUS_RECORD",
    name: "Kali Medical Status Record",
    short: "The projectile was removed after freezing; tissue response remains medically indeterminate.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  HUMAN_BULLET: {
    id: "HUMAN_BULLET",
    name: "Recovered Human Bullet",
    short: "A small piece of Hopo's fear, removed from the royal child and preserved for return.",
    art: "/images/game/ep2/items/workshop_clue.svg",
    artifact: true,
  },
  TRANSPORT_CRADLE: {
    id: "TRANSPORT_CRADLE",
    name: "Canvas Transport Cradle",
    short: "A hand-built sling that lets four people move a child without displaying a weapon.",
    art: "/images/game/ep2/items/kali_photo.svg",
  },
  KALI_IN_CRADLE: {
    id: "KALI_IN_CRADLE",
    name: "Kali · Protected Transfer",
    short: "The missing prince is covered, medically documented, and carried toward the royal line.",
    art: "/images/game/ep2/items/kali_photo.svg",
  },
  CONTACT_RECORD: {
    id: "CONTACT_RECORD",
    name: "Wordless Contact Record",
    short: "No translation occurred. Position, restraint, and the returned bullet carried the meaning.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  WORDLESS_RETURN: {
    id: "WORDLESS_RETURN",
    name: "The Wordless Return",
    short: "Kali crossed the line while Sung-ki and Ma'veyyo chose not to finish their fight.",
    art: "/images/game/ep2/items/kali_photo.svg",
    artifact: true,
  },
};

export const EP3_SCENES: Record<string, Scene> = {
  EP3_WITHDRAWAL: {
    id: "EP3_WITHDRAWAL",
    title: "Mountain Road · Broken Withdrawal Line",
    ambient: "The hunters have come down wounded. Sung-ae treats them while Sung-ki watches movement between the pines.",
    art: "/images/game/ep3/withdrawal.svg",
    exits: ["EP3_CLINIC"],
    hotspots: [
      { id: "SUNG_AE", label: "Sung-ae · Field Command", top: "30%", left: "60%", width: "18%", height: "48%" },
      { id: "WOUNDED_HUNTER", label: "Wounded Hunter", top: "54%", left: "32%", width: "25%", height: "28%" },
      { id: "RIFLE_RACK", label: "Loaded Hunting Rifles", top: "24%", left: "8%", width: "22%", height: "46%" },
      { id: "TREE_LINE", label: "Movement above the Road", top: "5%", left: "68%", width: "28%", height: "25%" },
    ],
  },
  EP3_CLINIC: {
    id: "EP3_CLINIC",
    title: "Hopo Health Center · Evacuation Desk",
    ambient: "The clinic has become a command room. Every bed is occupied and every official channel is silent.",
    art: "/images/game/ep3/clinic.svg",
    exits: ["EP3_WITHDRAWAL", "EP3_VILLAGE"],
    lockedUntil: "CLINIC_OPEN",
    hotspots: [
      { id: "HEALTH_CHIEF", label: "Health Center Chief", top: "22%", left: "58%", width: "18%", height: "48%" },
      { id: "NAKYEON", label: "Nak-yeon · Resident Coordinator", top: "30%", left: "15%", width: "18%", height: "44%" },
      { id: "EVAC_BOARD", label: "Evacuation Board", top: "8%", left: "34%", width: "22%", height: "32%" },
      { id: "DEAD_RADIO", label: "Dead District Radio", top: "62%", left: "76%", width: "18%", height: "22%" },
    ],
  },
  EP3_VILLAGE: {
    id: "EP3_VILLAGE",
    title: "Hopo Port · Witness Lane",
    ambient: "Families crowd the alley while Hae-sul repeats the creature's path with his whole body. Yang-bae guards the workshop door.",
    art: "/images/game/ep3/village.svg",
    exits: ["EP3_CLINIC", "EP3_COLD_ROOM", "EP3_FOREST_GATE"],
    lockedUntil: "VILLAGE_OPEN",
    hotspots: [
      { id: "HAESUL", label: "Hae-sul · Witness", top: "30%", left: "12%", width: "20%", height: "48%" },
      { id: "ASSEMBLY", label: "Civilian Assembly Point", top: "50%", left: "38%", width: "28%", height: "32%" },
      { id: "YANGBAE", label: "Yang-bae · Workshop Door", top: "22%", left: "70%", width: "18%", height: "52%" },
      { id: "FUEL_SHED", label: "Fuel and Evidence Shed", top: "62%", left: "4%", width: "18%", height: "25%" },
    ],
  },
  EP3_COLD_ROOM: {
    id: "EP3_COLD_ROOM",
    title: "Yang-bae's Workshop · Cold Room",
    ambient: "The compressor shudders. Kali remains beneath canvas while the forest closes around the village.",
    art: "/images/game/ep3/cold_room.svg",
    exits: ["EP3_VILLAGE"],
    lockedUntil: "COLD_ROOM_OPEN",
    hotspots: [
      { id: "KALI", label: "Kali · Frozen Child", top: "30%", left: "26%", width: "38%", height: "48%" },
      { id: "HANDCART", label: "Canvas Handcart", top: "54%", left: "66%", width: "26%", height: "30%" },
      { id: "COMPRESSOR", label: "Failing Compressor", top: "8%", left: "70%", width: "20%", height: "34%" },
      { id: "DRAIN", label: "Meltwater Drain", top: "78%", left: "10%", width: "32%", height: "16%" },
    ],
  },
  EP3_FOREST_GATE: {
    id: "EP3_FOREST_GATE",
    title: "Forest Margin · Silent Corridor",
    ambient: "Aydobor's marks divide the trees. One path shadows the evacuees; another path leaves them room to pass.",
    art: "/images/game/ep3/forest_gate.svg",
    exits: ["EP3_VILLAGE", "EP3_EXCHANGE"],
    lockedUntil: "FOREST_GATE_OPEN",
    hotspots: [
      { id: "CANOPY", label: "Aydobor in the Canopy", top: "4%", left: "58%", width: "25%", height: "32%" },
      { id: "TREE_MARKS", label: "Axe Marks and Decoys", top: "26%", left: "8%", width: "28%", height: "44%" },
      { id: "ROUTE_MARKER", label: "Civilian Route Marker", top: "60%", left: "38%", width: "26%", height: "26%" },
      { id: "CHECKPOINT", label: "Human Firing Checkpoint", top: "46%", left: "70%", width: "24%", height: "34%" },
    ],
  },
  EP3_EXCHANGE: {
    id: "EP3_EXCHANGE",
    title: "Burned Grove · Wordless Exchange",
    ambient: "Zor waits beyond the burned trees. Ma'veyyo and Sung-ki face each other while Aydobor watches the covered cradle.",
    art: "/images/game/ep3/exchange.svg",
    exits: ["EP3_FOREST_GATE"],
    lockedUntil: "EXCHANGE_OPEN",
    hotspots: [
      { id: "MAVEYYO", label: "Ma'veyyo · Royal Guard", top: "20%", left: "38%", width: "22%", height: "58%" },
      { id: "SUNGKI_LINE", label: "Sung-ki · Human Line", top: "34%", left: "66%", width: "22%", height: "48%" },
      { id: "ROYAL_LINE", label: "Zor · Return Boundary", top: "12%", left: "6%", width: "28%", height: "54%" },
      { id: "EVAC_EXIT", label: "Open Civilian Corridor", top: "70%", left: "58%", width: "34%", height: "22%" },
    ],
  },
};

export const EP3_ENDINGS: Record<EndingId, EndingDescriptor> = {
  A: {
    id: "A",
    title: "Ending A — Dust over Hopo",
    body: "The withdrawal clock expires. Hopo's records, routes, and names scatter under retaliatory fire until each side remembers only what the other destroyed.",
  },
  B: {
    id: "B",
    title: "Ending B — No Heir, No Truce",
    body: "Kali and the evidence of the human first shot burn together. Zor receives smoke instead of her child, and Ma'veyyo's recovery mission becomes permanent war.",
    isRestart: true,
  },
  C: {
    id: "C",
    title: "Ending C — The Evacuation Line",
    body: "The flare and disarmed checkpoint hold long enough for Nak-yeon's manifest to clear the village. Hopo's people and causal record survive, though Kali's fate remains unresolved.",
    grantsArtifacts: ["CIVILIAN_MANIFEST", "EVAC_ROUTE", "CONTACT_RECORD"],
    unlocksNextEpisode: true,
  },
  D: {
    id: "D",
    title: "Ending D — The Wordless Return",
    body: "The human bullet crosses the boundary beside Kali. Sung-ki lowers his hands; Ma'veyyo does not finish the charge. No word is translated, but the child returns and a fragile truce begins.",
    grantsArtifacts: ["KALI_STATUS_RECORD", "CONTACT_RECORD", "WORDLESS_RETURN"],
    unlocksNextEpisode: true,
  },
};

export const EP3_INTERACTIONS: Interaction[] = [
  // BROKEN WITHDRAWAL LINE
  {
    id: "ep3.withdrawal.sungae.prepare",
    scene: "EP3_WITHDRAWAL",
    hotspot: "SUNG_AE",
    requires: { flagsNone: ["FIELD_COMMAND_READY"] },
    grants: ["TRAUMA_KIT", "CEASEFIRE_FLARE"],
    setFlags: ["FIELD_COMMAND_READY"],
    log: { role: "SUNG-AE", text: "'One kit, one flare. Save people first. If the flare burns, nobody shoots through it.'", kind: "voice" },
    once: true,
  },
  { id: "ep3.withdrawal.sungae.idle", scene: "EP3_WITHDRAWAL", hotspot: "SUNG_AE", log: { role: "SUNG-AE", text: "'The road is not a front line until we make it one.'", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.withdrawal.hunter.treat",
    scene: "EP3_WITHDRAWAL",
    hotspot: "WOUNDED_HUNTER",
    requires: { item: "TRAUMA_KIT", flagsNone: ["CASUALTIES_STABILIZED"] },
    grants: ["CASUALTY_LEDGER"],
    setFlags: ["CASUALTIES_STABILIZED", "CLINIC_OPEN"],
    log: { role: "SYSTEM", text: "Sung-ae's tags turn a heap of bodies into names, wounds, and an order of evacuation.", kind: "system" },
    once: true,
  },
  { id: "ep3.withdrawal.hunter.idle", scene: "EP3_WITHDRAWAL", hotspot: "WOUNDED_HUNTER", log: { role: "SYSTEM", text: "A hunter presses both hands over a wound. The health center needs a count before it can move anyone.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.withdrawal.rifles.secure",
    scene: "EP3_WITHDRAWAL",
    hotspot: "RIFLE_RACK",
    requires: { flagsNone: ["WEAPONS_SECURED"] },
    grants: ["RIFLE_BOLTS"],
    setFlags: ["WEAPONS_SECURED"],
    log: { role: "BUM-SEOK", text: "'Remove every bolt. If they need proof that we came without a first shot, let them see the rifles cannot fire.'", kind: "system" },
    once: true,
  },
  { id: "ep3.withdrawal.rifles.idle", scene: "EP3_WITHDRAWAL", hotspot: "RIFLE_RACK", log: { role: "SYSTEM", text: "The rifles remain, but their actions are locked in your evidence bag.", kind: "default" }, turnCost: 0 },
  { id: "ep3.withdrawal.trees", scene: "EP3_WITHDRAWAL", hotspot: "TREE_LINE", log: { role: "SUNG-KI", text: "'Something is keeping pace above us. It could have struck the wounded already. It has not.'", kind: "omega" }, turnCost: 0 },

  // HEALTH CENTER
  {
    id: "ep3.clinic.chief.accept",
    scene: "EP3_CLINIC",
    hotspot: "HEALTH_CHIEF",
    requires: { item: "FIRST_SHOT_REPORT", flag: "CASUALTIES_STABILIZED", flagsNone: ["TRANSFER_AUTHORIZED"] },
    grants: ["TRANSFER_ORDER"],
    setFlags: ["TRANSFER_AUTHORIZED", "VILLAGE_OPEN"],
    log: { role: "HEALTH CHIEF", text: "'Then Kali is a gunshot patient before he is anything else. We move him under medical custody, not as bait.'", kind: "system" },
    once: true,
  },
  { id: "ep3.clinic.chief.idle", scene: "EP3_CLINIC", hotspot: "HEALTH_CHIEF", log: { role: "HEALTH CHIEF", text: "'Bring me the causal report. I will not sign a transfer based on another rumor.'", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.clinic.nakyeon.map",
    scene: "EP3_CLINIC",
    hotspot: "NAKYEON",
    requires: { item: "CASUALTY_LEDGER", flagsNone: ["CIVILIANS_COUNTED"] },
    grants: ["EVAC_MAP"],
    setFlags: ["CIVILIANS_COUNTED"],
    log: { role: "NAK-YEON", text: "'The police map forgets half the village. These cellars and drains are how our old people will get out.'", kind: "voice" },
    once: true,
  },
  { id: "ep3.clinic.nakyeon.idle", scene: "EP3_CLINIC", hotspot: "NAKYEON", log: { role: "NAK-YEON", text: "'Count the people who cannot run. A route without their names is only a line on paper.'", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.clinic.board.mark",
    scene: "EP3_CLINIC",
    hotspot: "EVAC_BOARD",
    requires: { item: "EVAC_MAP", has: ["CASUALTY_LEDGER"], flagsNone: ["EVAC_SECTORS_MARKED"] },
    setFlags: ["EVAC_SECTORS_MARKED"],
    log: { role: "SYSTEM", text: "Nak-yeon's footpaths divide Hopo into evacuation sectors that avoid the armed road.", kind: "system" },
    once: true,
  },
  { id: "ep3.clinic.board.idle", scene: "EP3_CLINIC", hotspot: "EVAC_BOARD", log: { role: "SYSTEM", text: "The official arrows all point to the road where the firing line collapsed.", kind: "default" }, turnCost: 0 },
  { id: "ep3.clinic.radio", scene: "EP3_CLINIC", hotspot: "DEAD_RADIO", log: { role: "RADIO", text: "No district command. No translation. Hopo will have to make its meaning visible.", kind: "danger" }, turnCost: 0 },

  // WITNESS LANE
  {
    id: "ep3.village.haesul.record",
    scene: "EP3_VILLAGE",
    hotspot: "HAESUL",
    requires: { flagsNone: ["SEARCH_BEHAVIOR_MAPPED"] },
    grants: ["HAESUL_SKETCH"],
    setFlags: ["SEARCH_BEHAVIOR_MAPPED"],
    log: { role: "HAE-SUL", text: "'It moved above me—axe here, body there—but it kept this side empty. It was herding me away, not closing in.'", kind: "omega" },
    once: true,
  },
  { id: "ep3.village.haesul.idle", scene: "EP3_VILLAGE", hotspot: "HAESUL", log: { role: "SYSTEM", text: "Hae-sul repeats the same three movements. The pattern matters more than his vocabulary.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.village.assembly.manifest",
    scene: "EP3_VILLAGE",
    hotspot: "ASSEMBLY",
    requires: { item: "CASUALTY_LEDGER", has: ["EVAC_MAP"], flagsAll: ["EVAC_SECTORS_MARKED"], flagsNone: ["VILLAGE_READY"] },
    grants: ["CIVILIAN_MANIFEST"],
    setFlags: ["VILLAGE_READY", "FOREST_GATE_OPEN"],
    log: { role: "SYSTEM", text: "Each cellar group receives a route and a name check. The village can now move without becoming a panicked column.", kind: "system" },
    once: true,
  },
  { id: "ep3.village.assembly.idle", scene: "EP3_VILLAGE", hotspot: "ASSEMBLY", log: { role: "SYSTEM", text: "Families wait for an order that includes the wounded, the old, and the missing.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.village.yangbae.open",
    scene: "EP3_VILLAGE",
    hotspot: "YANGBAE",
    requires: { item: "FIRST_SHOT_REPORT", has: ["TRANSFER_ORDER"], flagsNone: ["COLD_ROOM_OPEN"] },
    setFlags: ["COLD_ROOM_OPEN", "YANGBAE_YIELDED"] ,
    log: { role: "YANG-BAE", text: "'Take him out the front. No more hiding. If they came for the child, let them see who put the bullet there.'", kind: "danger" },
    once: true,
  },
  { id: "ep3.village.yangbae.idle", scene: "EP3_VILLAGE", hotspot: "YANGBAE", log: { role: "YANG-BAE", text: "'The compressor is failing. Decide whether you are moving a body or returning a child.'", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.village.fuel.take",
    scene: "EP3_VILLAGE",
    hotspot: "FUEL_SHED",
    requires: { flagsNone: ["FUEL_TAKEN"] },
    grants: ["KEROSENE_CAN"],
    setFlags: ["FUEL_TAKEN"],
    log: { role: "SYSTEM", text: "A kerosene can sits beside old case paper. Fire would erase the evidence faster than any official order.", kind: "danger" },
    once: true,
  },
  { id: "ep3.village.fuel.idle", scene: "EP3_VILLAGE", hotspot: "FUEL_SHED", log: { role: "SYSTEM", text: "An empty shelf smells of fuel and wet timber.", kind: "default" }, turnCost: 0 },

  // COLD ROOM
  {
    id: "ep3.cold.kali.destroy",
    scene: "EP3_COLD_ROOM",
    hotspot: "KALI",
    requires: { item: "KEROSENE_CAN" },
    destroys: ["KEROSENE_CAN"],
    triggersEnding: "B",
    log: { role: "SYSTEM", text: "Fuel spreads under the canvas. The easiest way to end the evidence is also the surest way to begin a war.", kind: "danger" },
    once: true,
  },
  {
    id: "ep3.cold.kali.examine",
    scene: "EP3_COLD_ROOM",
    hotspot: "KALI",
    requires: { item: "TRANSFER_ORDER", flagsNone: ["KALI_EXAMINED"] },
    grants: ["KALI_STATUS_RECORD", "HUMAN_BULLET"],
    setFlags: ["KALI_EXAMINED"],
    log: { role: "HEALTH CHIEF", text: "'Human projectile recovered. The cold preserved the wound, but I cannot certify death in a body whose biology I do not know.'", kind: "omega" },
    once: true,
  },
  {
    id: "ep3.cold.kali.load",
    scene: "EP3_COLD_ROOM",
    hotspot: "KALI",
    requires: { item: "TRANSPORT_CRADLE", has: ["KALI_STATUS_RECORD", "HUMAN_BULLET"], flag: "KALI_EXAMINED", flagsNone: ["KALI_SECURED"] },
    consumes: ["TRANSPORT_CRADLE"],
    grants: ["KALI_IN_CRADLE"],
    setFlags: ["KALI_SECURED"],
    log: { role: "SYSTEM", text: "Four hands lift the covered child. The wound record is tied outside the canvas where both lines can see it.", kind: "system" },
    once: true,
  },
  { id: "ep3.cold.kali.idle", scene: "EP3_COLD_ROOM", hotspot: "KALI", log: { role: "SYSTEM", text: "Kali cannot be carried safely until the health chief documents the wound and the handcart becomes a cradle.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.cold.handcart.build",
    scene: "EP3_COLD_ROOM",
    hotspot: "HANDCART",
    requires: { flagsNone: ["CRADLE_BUILT"] },
    grants: ["TRANSPORT_CRADLE"],
    setFlags: ["CRADLE_BUILT"],
    log: { role: "SYSTEM", text: "Canvas from the mannequin racks becomes a four-hand cradle. Nothing about it resembles a cage or weapons platform.", kind: "system" },
    once: true,
  },
  { id: "ep3.cold.handcart.idle", scene: "EP3_COLD_ROOM", hotspot: "HANDCART", log: { role: "SYSTEM", text: "The handcart is stripped to a canvas sling and carrying poles.", kind: "default" }, turnCost: 0 },
  { id: "ep3.cold.compressor", scene: "EP3_COLD_ROOM", hotspot: "COMPRESSOR", log: { role: "SYSTEM", text: "The compressor temperature is rising. Waiting will make the choice for you.", kind: "danger" }, turnCost: 0 },
  { id: "ep3.cold.drain", scene: "EP3_COLD_ROOM", hotspot: "DRAIN", log: { role: "SYSTEM", text: "Meltwater carries no green blood—only rust, frost, and the residue of Yang-bae's floor.", kind: "default" }, turnCost: 0 },

  // FOREST MARGIN
  {
    id: "ep3.gate.canopy.observe",
    scene: "EP3_FOREST_GATE",
    hotspot: "CANOPY",
    requires: { flagsNone: ["AYDOBOR_OBSERVED"] },
    setFlags: ["AYDOBOR_OBSERVED"],
    log: { role: "SYSTEM", text: "Aydobor changes trees whenever the cradle moves. The axe tracks the child, not the evacuees.", kind: "omega" },
    once: true,
  },
  { id: "ep3.gate.canopy.idle", scene: "EP3_FOREST_GATE", hotspot: "CANOPY", log: { role: "SYSTEM", text: "A branch bends. The open corridor remains open.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.gate.marks.decode",
    scene: "EP3_FOREST_GATE",
    hotspot: "TREE_MARKS",
    requires: { item: "HAESUL_SKETCH", flag: "AYDOBOR_OBSERVED", flagsNone: ["SAFE_CORRIDOR"] },
    setFlags: ["SAFE_CORRIDOR", "EXCHANGE_OPEN"],
    log: { role: "SYSTEM", text: "Hae-sul's motions match the axe marks. The blocked path follows Kali; the untouched drainage path is a deliberate civilian corridor.", kind: "system" },
    once: true,
  },
  { id: "ep3.gate.marks.idle", scene: "EP3_FOREST_GATE", hotspot: "TREE_MARKS", log: { role: "SYSTEM", text: "Some cuts are warnings; others are decoys. Hae-sul saw the order in which they were made.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.gate.route.mark",
    scene: "EP3_FOREST_GATE",
    hotspot: "ROUTE_MARKER",
    requires: { item: "EVAC_MAP", has: ["CIVILIAN_MANIFEST"], flag: "SAFE_CORRIDOR", flagsNone: ["EVAC_READY"] },
    grants: ["EVAC_ROUTE"],
    setFlags: ["EVAC_READY"],
    log: { role: "NAK-YEON", text: "'Cellar groups move through the drainage cut. Nobody follows the cradle, and nobody leaves a name behind.'", kind: "system" },
    once: true,
  },
  { id: "ep3.gate.route.idle", scene: "EP3_FOREST_GATE", hotspot: "ROUTE_MARKER", log: { role: "SYSTEM", text: "A safe corridor is useless until every civilian group is assigned to it.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.gate.checkpoint.disarm",
    scene: "EP3_FOREST_GATE",
    hotspot: "CHECKPOINT",
    requires: { item: "RIFLE_BOLTS", flag: "WEAPONS_SECURED", flagsNone: ["MUZZLES_DOWN"] },
    setFlags: ["MUZZLES_DOWN"],
    log: { role: "SUNG-KI", text: "'Show the bolts on the white cloth. If anyone loads another rifle, they answer to me first.'", kind: "voice" },
    once: true,
  },
  { id: "ep3.gate.checkpoint.idle", scene: "EP3_FOREST_GATE", hotspot: "CHECKPOINT", log: { role: "SYSTEM", text: "The firing bags point toward the exchange ground. Visible disarmament must happen before contact.", kind: "default" }, turnCost: 0 },

  // WORDLESS EXCHANGE
  {
    id: "ep3.exchange.maveyyo.observe",
    scene: "EP3_EXCHANGE",
    hotspot: "MAVEYYO",
    requires: { flagsNone: ["NO_FIRST_STRIKE"] },
    setFlags: ["NO_FIRST_STRIKE"],
    log: { role: "BUM-SEOK", text: "Ma'veyyo's body lowers to charge, yet it waits between Zor and the cradle. The guard is holding a line, not beginning one.", kind: "omega" },
    once: true,
  },
  { id: "ep3.exchange.maveyyo.idle", scene: "EP3_EXCHANGE", hotspot: "MAVEYYO", log: { role: "SYSTEM", text: "The guard follows Sung-ki's hands. A fist will be read before any report.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.exchange.sungki.flare",
    scene: "EP3_EXCHANGE",
    hotspot: "SUNGKI_LINE",
    requires: { item: "CEASEFIRE_FLARE", flagsAll: ["MUZZLES_DOWN", "SAFE_CORRIDOR", "NO_FIRST_STRIKE"], flagsNone: ["HOLDING_FIRE"] },
    consumes: ["CEASEFIRE_FLARE"],
    setFlags: ["HOLDING_FIRE"],
    log: { role: "SYSTEM", text: "Red light fills the grove. Sung-ki opens both hands. Ma'veyyo stops one stride before the human line.", kind: "system" },
    once: true,
  },
  { id: "ep3.exchange.sungki.idle", scene: "EP3_EXCHANGE", hotspot: "SUNGKI_LINE", log: { role: "SUNG-KI", text: "'Give me a signal every frightened man behind me can understand.'", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.exchange.royal.bullet",
    scene: "EP3_EXCHANGE",
    hotspot: "ROYAL_LINE",
    requires: { item: "HUMAN_BULLET", has: ["KALI_IN_CRADLE", "FIRST_SHOT_REPORT"], flagsAll: ["HOLDING_FIRE", "NO_FIRST_STRIKE"], flagsNone: ["BULLET_SURRENDERED"] },
    setFlags: ["BULLET_SURRENDERED"],
    log: { role: "SYSTEM", text: "The recovered bullet is placed on the boundary cloth. Zor looks from the metal to Kali's covered wound. Cause becomes visible without a shared word.", kind: "omega" },
    once: true,
  },
  {
    id: "ep3.exchange.royal.return",
    scene: "EP3_EXCHANGE",
    hotspot: "ROYAL_LINE",
    requires: { item: "KALI_IN_CRADLE", has: ["KALI_STATUS_RECORD", "HUMAN_BULLET", "FIRST_SHOT_REPORT"], flagsAll: ["HOLDING_FIRE", "BULLET_SURRENDERED", "NO_FIRST_STRIKE", "AYDOBOR_OBSERVED"] },
    consumes: ["KALI_IN_CRADLE", "HUMAN_BULLET"],
    grants: ["CONTACT_RECORD", "WORDLESS_RETURN"],
    setFlags: ["KALI_RETURNED", "TRUCE_OPEN"] ,
    triggersEnding: "D",
    log: { role: "SYSTEM", text: "The cradle crosses. Aydobor receives Kali; Zor shields the child; Ma'veyyo lets Sung-ki step backward alive.", kind: "omega" },
    once: true,
  },
  { id: "ep3.exchange.royal.idle", scene: "EP3_EXCHANGE", hotspot: "ROYAL_LINE", log: { role: "SYSTEM", text: "Zor waits for the missing child and for an act that explains the human weapon in his body.", kind: "default" }, turnCost: 0 },
  {
    id: "ep3.exchange.evac.complete",
    scene: "EP3_EXCHANGE",
    hotspot: "EVAC_EXIT",
    requires: { item: "CIVILIAN_MANIFEST", has: ["EVAC_ROUTE"], flagsAll: ["HOLDING_FIRE", "SAFE_CORRIDOR", "MUZZLES_DOWN", "EVAC_READY"] },
    grants: ["CONTACT_RECORD"],
    setFlags: ["CIVILIANS_EVACUATED"] ,
    triggersEnding: "C",
    log: { role: "SYSTEM", text: "Nak-yeon calls each name once. The last cellar group clears the grove while the royal line remains fixed on Kali.", kind: "system" },
    once: true,
  },
  { id: "ep3.exchange.evac.idle", scene: "EP3_EXCHANGE", hotspot: "EVAC_EXIT", log: { role: "SYSTEM", text: "The corridor is open, but an evacuation without a manifest will leave people behind.", kind: "default" }, turnCost: 0 },
];

export const EP3_INITIAL_LOGS = [
  { turn: 1, role: "SYSTEM", text: "EPISODE 3 · HUMAN DUST", kind: "system" as const },
  { turn: 1, role: "SUNG-AE", text: "'The hunters are back. Some of them. The forest kept pace with us all the way down.'", kind: "voice" as const },
  { turn: 1, role: "BUM-SEOK", text: "Yang-bae's first shot is proven. Proof will not stop the next shot unless Hopo makes it visible.", kind: "omega" as const },
  { turn: 1, role: "SYSTEM", text: "OBJECTIVE · Stabilize the withdrawal, evacuate the village, and return Kali without turning him into a weapon.", kind: "danger" as const },
];

export const EPISODE_3: GameDefinition = {
  id: "ep3",
  number: 3,
  version: 1,
  title: "Human Dust",
  headerLabel: "HOPO INCIDENT · EPISODE 3",
  maxTurns: EP3_MAX_TURNS,
  storageKey: "nahope_game_ep3_v1",
  scenes: EP3_SCENES,
  sceneOrder: ["EP3_WITHDRAWAL", "EP3_CLINIC", "EP3_VILLAGE", "EP3_COLD_ROOM", "EP3_FOREST_GATE", "EP3_EXCHANGE"],
  items: EP3_ITEMS,
  interactions: EP3_INTERACTIONS,
  endings: EP3_ENDINGS,
  initialScene: "EP3_WITHDRAWAL" as SceneId,
  initialLogs: EP3_INITIAL_LOGS,
  initialInventory: ["FIRST_SHOT_REPORT"],
  waitText: "You wait. The cold room warms, the civilian line frays, and two armed species study the same boundary.",
  successfulEndings: ["C", "D"],
  caseRecord: {
    title: "Contact Record · Human Dust",
    rows: [
      { label: "Human casualties", text: "named, triaged, and assigned an evacuation order", revealFlag: "CASUALTIES_STABILIZED" },
      { label: "Human weapons", text: "rifle actions removed and displayed before contact", revealFlag: "MUZZLES_DOWN" },
      { label: "Forest behavior", text: "Aydobor tracked Kali while leaving a civilian corridor", revealFlag: "SAFE_CORRIDOR" },
      { label: "Kali status", text: "human projectile recovered; alien tissue response indeterminate", revealFlag: "KALI_EXAMINED" },
      { label: "Contact behavior", text: "Ma'veyyo held position until human restraint became visible", revealFlag: "NO_FIRST_STRIKE" },
    ],
    notes: [
      { text: "Nak-yeon manifest · residents moved by lived routes, not the failed firing road", revealFlag: "VILLAGE_READY" },
      { text: "wordless syntax · disarmament, returned bullet, returned child", revealFlag: "BULLET_SURRENDERED" },
    ],
  },
};
