import type {
  EndingDescriptor,
  EndingId,
  GameDefinition,
  Interaction,
  Item,
  Scene,
  SceneId,
} from "./types";

export const EP4_MAX_TURNS = 42;

export const EP4_ITEMS: Record<string, Item> = {
  OMEGA_DIRECTIVE: {
    id: "OMEGA_DIRECTIVE",
    name: "Omega Archive Directive",
    short: "Separate evidence, interpretation, and invention before transmitting the Hopo record.",
    art: "/images/game/ep2/items/report.svg",
  },
  ELITE_ARTIFACT_LEDGER: {
    id: "ELITE_ARTIFACT_LEDGER",
    name: "Verified Artifact Ledger",
    short: "Server-authorized proof that this custodian carries at least three records from Hopo.",
    art: "/images/game/ep2/items/hull_fragment.svg",
  },
  CHAIN_OF_CUSTODY: {
    id: "CHAIN_OF_CUSTODY",
    name: "Surviving Chain of Custody",
    short: "A transfer ledger connecting Bum-seok's field case to the later classified archive.",
    art: "/images/game/ep2/items/report.svg",
  },
  FIELD_TESTIMONY: {
    id: "FIELD_TESTIMONY",
    name: "Bum-seok Field Testimony",
    short: "A damaged recording that distinguishes what Bum-seok witnessed from what he feared.",
    art: "/images/game/ep2/items/report.svg",
  },
  INCIDENT_ARCHIVE: {
    id: "INCIDENT_ARCHIVE",
    name: "Hopo Incident Archive",
    short: "Cattle evidence, Kali's wound record, the crash structure, and the evacuation outcome.",
    art: "/images/game/ep2/items/workshop_clue.svg",
  },
  TIGER_REBUTTAL: {
    id: "TIGER_REBUTTAL",
    name: "Tiger Hypothesis Rebuttal",
    short: "The cattle wounds and oversized tracks do not support an ordinary predator.",
    art: "/images/game/ep2/items/report.svg",
  },
  CAUSALITY_SEQUENCE: {
    id: "CAUSALITY_SEQUENCE",
    name: "First-shot Causality Sequence",
    short: "Yang-bae's human bullet struck Kali before the royal survivors closed around Hopo.",
    art: "/images/game/ep2/items/kali_photo.svg",
  },
  CONTACT_OUTCOME: {
    id: "CONTACT_OUTCOME",
    name: "Wordless Contact Outcome",
    short: "Visible disarmament, evacuation, and Kali's return interrupted retaliation without translation.",
    art: "/images/game/ep2/items/ceasefire_flare.svg",
  },
  VERIFIED_TIMELINE: {
    id: "VERIFIED_TIMELINE",
    name: "Verified Hopo Timeline",
    short: "A causal record that preserves the human first shot without declaring either species innocent.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  PROVEN_FACTS: {
    id: "PROVEN_FACTS",
    name: "Proven Facts Register",
    short: "Claims supported by physical evidence, photographs, or converging testimony.",
    art: "/images/game/ep2/items/report.svg",
  },
  SUPPORTED_INFERENCES: {
    id: "SUPPORTED_INFERENCES",
    name: "Supported Inferences Register",
    short: "Strong readings of alien behavior that were never translated into human language.",
    art: "/images/game/ep2/items/search_map.svg",
  },
  CREATIVE_BOUNDARY: {
    id: "CREATIVE_BOUNDARY",
    name: "Creative Boundary Notice",
    short: "A visible border preventing a sequel proposal from masquerading as historical evidence.",
    art: "/images/game/ep2/items/report.svg",
  },
  LAYERED_ARCHIVE: {
    id: "LAYERED_ARCHIVE",
    name: "Three-layer Hopo Archive",
    short: "Fact, inference, and proposal remain readable without collapsing into one official story.",
    art: "/images/game/ep2/items/hull_fragment.svg",
    artifact: true,
  },
  KALI_QUESTION: {
    id: "KALI_QUESTION",
    name: "Kali Continuity Question",
    short: "Does Kali recover, survive as memory, or become the unanswered center of the next contact?",
    art: "/images/game/ep2/items/kali_photo.svg",
  },
  ZOR_QUESTION: {
    id: "ZOR_QUESTION",
    name: "Zor Judgment Question",
    short: "Does the empress forgive humanity, defer judgment, or summon humans to answer for Hopo?",
    art: "/images/game/ep2/items/hull_fragment.svg",
  },
  WITNESS_QUESTION: {
    id: "WITNESS_QUESTION",
    name: "Human Witness Question",
    short: "Will Bum-seok, Sung-ki, Sung-ae, Nak-yeon, and Hae-sul remain witnesses or become evidence themselves?",
    art: "/images/game/ep2/items/report.svg",
  },
  HUMANS_IN_SPACE_DRAFT: {
    id: "HUMANS_IN_SPACE_DRAFT",
    name: "Humans in Space Draft",
    short: "A game-original sequel framework that sends humanity into Gertu space as accountable witnesses.",
    art: "/images/game/ep2/items/search_map.svg",
    artifact: true,
  },
  ARTIFACT_TRIAD: {
    id: "ARTIFACT_TRIAD",
    name: "Artifact Triad Verification",
    short: "Three or more retained Hopo artifacts have passed the archive's provenance check.",
    art: "/images/game/ep2/items/hull_fragment.svg",
  },
  AUTHORSHIP_RECORD: {
    id: "AUTHORSHIP_RECORD",
    name: "Custodian Authorship Record",
    short: "The creative choices are attributed to the player instead of being inserted into film canon.",
    art: "/images/game/ep2/items/report.svg",
  },
  GOVERNANCE_PACKET: {
    id: "GOVERNANCE_PACKET",
    name: "Community Governance Packet",
    short: "The layered archive, artifact proof, and attributed scenario are ready for public review.",
    art: "/images/game/ep2/items/ceasefire_flare.svg",
    artifact: true,
  },
  OPEN_ARCHIVE_INDEX: {
    id: "OPEN_ARCHIVE_INDEX",
    name: "Open Archive Index",
    short: "Every claim exposes its evidence level and can be challenged by the Hopo community.",
    art: "/images/game/ep2/items/report.svg",
    artifact: true,
  },
  HOPE_PROTOCOL: {
    id: "HOPE_PROTOCOL",
    name: "Hope Protocol Transmission",
    short: "The Hopo record becomes an invitation to choose differently at the next contact.",
    art: "/images/game/ep2/items/ceasefire_flare.svg",
    artifact: true,
  },
};

export const EP4_SCENES: Record<string, Scene> = {
  EP4_ARCHIVE: {
    id: "EP4_ARCHIVE",
    title: "Classified Intake · Surviving Archive",
    ambient: "Years after Hopo, a damaged archive waits between a deletion order and an unnamed custodian.",
    art: "/images/game/ep4/archive.svg",
    exits: ["EP4_TIMELINE"],
    hotspots: [
      { id: "INTAKE_TERMINAL", label: "Custodian Intake Terminal", top: "20%", left: "8%", width: "24%", height: "50%" },
      { id: "BUMSEOK_RECORDER", label: "Bum-seok's Damaged Recorder", top: "58%", left: "38%", width: "24%", height: "25%" },
      { id: "SEALED_CASES", label: "Sealed Hopo Case Boxes", top: "18%", left: "64%", width: "28%", height: "54%" },
      { id: "BURN_ORDER", label: "Automatic Redaction Furnace", top: "4%", left: "38%", width: "22%", height: "28%" },
    ],
  },
  EP4_TIMELINE: {
    id: "EP4_TIMELINE",
    title: "Causality Lab · Hopo Timeline",
    ambient: "The archive contains every event and several incompatible orders in which officials want them remembered.",
    art: "/images/game/ep4/timeline.svg",
    exits: ["EP4_ARCHIVE", "EP4_CLASSIFIER"],
    lockedUntil: "ARCHIVE_ADMITTED",
    hotspots: [
      { id: "CATTLE_PANEL", label: "Cattle-site Origin Panel", top: "18%", left: "6%", width: "24%", height: "50%" },
      { id: "FIRST_SHOT_PANEL", label: "Kali First-shot Panel", top: "18%", left: "36%", width: "26%", height: "50%" },
      { id: "TRUCE_PANEL", label: "Wordless Contact Panel", top: "18%", left: "68%", width: "25%", height: "50%" },
      { id: "SEQUENCE_BOARD", label: "Causal Sequence Board", top: "70%", left: "26%", width: "48%", height: "22%" },
    ],
  },
  EP4_CLASSIFIER: {
    id: "EP4_CLASSIFIER",
    title: "Evidence Chamber · Three Layers",
    ambient: "Three terminals ask the same question in different forms: what happened, what does it suggest, and what do you want next?",
    art: "/images/game/ep4/classifier.svg",
    exits: ["EP4_TIMELINE", "EP4_SCENARIO"],
    lockedUntil: "TIMELINE_VERIFIED",
    hotspots: [
      { id: "FACT_TERMINAL", label: "Proven Fact Terminal", top: "20%", left: "5%", width: "26%", height: "48%" },
      { id: "INFERENCE_TERMINAL", label: "Supported Inference Terminal", top: "20%", left: "37%", width: "26%", height: "48%" },
      { id: "PROPOSAL_TERMINAL", label: "Creative Proposal Terminal", top: "20%", left: "69%", width: "26%", height: "48%" },
      { id: "SCHEMA_CONSOLE", label: "Layered Archive Console", top: "70%", left: "28%", width: "44%", height: "22%" },
    ],
  },
  EP4_SCENARIO: {
    id: "EP4_SCENARIO",
    title: "Scenario Lab · Humans in Space",
    ambient: "The sequel room does not predict the future. It makes every invention sign its own name.",
    art: "/images/game/ep4/scenario.svg",
    exits: ["EP4_CLASSIFIER", "EP4_GOVERNANCE"],
    lockedUntil: "CLASSIFICATION_COMPLETE",
    hotspots: [
      { id: "KALI_FORK", label: "Kali Continuity Fork", top: "18%", left: "7%", width: "25%", height: "50%" },
      { id: "ZOR_FORK", label: "Zor Judgment Fork", top: "18%", left: "38%", width: "25%", height: "50%" },
      { id: "WITNESS_FORK", label: "Human Witness Fork", top: "18%", left: "69%", width: "24%", height: "50%" },
      { id: "MISSION_TABLE", label: "Humans in Space Mission Table", top: "70%", left: "24%", width: "52%", height: "22%" },
    ],
  },
  EP4_GOVERNANCE: {
    id: "EP4_GOVERNANCE",
    title: "Community Relay · Governance Desk",
    ambient: "A scenario cannot become collective memory until its evidence, author, and audience remain visible.",
    art: "/images/game/ep4/governance.svg",
    exits: ["EP4_SCENARIO", "EP4_TRANSMISSION"],
    lockedUntil: "SCENARIO_FRAME_READY",
    hotspots: [
      { id: "ARTIFACT_READER", label: "Three-artifact Provenance Reader", top: "18%", left: "6%", width: "26%", height: "50%" },
      { id: "AUTHORSHIP_CONSOLE", label: "Player Authorship Console", top: "18%", left: "38%", width: "26%", height: "50%" },
      { id: "PUBLIC_LEDGER", label: "Community Review Ledger", top: "18%", left: "70%", width: "24%", height: "50%" },
      { id: "MILITARY_UPLINK", label: "Restricted Military Uplink", top: "70%", left: "30%", width: "40%", height: "22%" },
    ],
  },
  EP4_TRANSMISSION: {
    id: "EP4_TRANSMISSION",
    title: "Omega Relay · Final Transmission",
    ambient: "The last console offers no correct future—only different uses for the same surviving truth.",
    art: "/images/game/ep4/transmission.svg",
    exits: ["EP4_GOVERNANCE"],
    lockedUntil: "GOVERNANCE_READY",
    hotspots: [
      { id: "PUBLIC_MIRROR", label: "Open Archive Mirror", top: "20%", left: "8%", width: "26%", height: "52%" },
      { id: "ARCHIVE_EXIT", label: "Publish Archive Only", top: "20%", left: "38%", width: "24%", height: "52%" },
      { id: "OMEGA_RELAY", label: "Submit Hope Protocol", top: "20%", left: "68%", width: "25%", height: "52%" },
      { id: "SIGNAL_WINDOW", label: "Unanswered Signal Window", top: "72%", left: "28%", width: "44%", height: "20%" },
    ],
  },
};

export const EP4_ENDINGS: Record<EndingId, EndingDescriptor> = {
  A: {
    id: "A",
    title: "Ending A — The Redaction",
    body: "The surviving archive is deleted, sealed, or allowed to expire. At the next contact, humanity will again begin with a convenient name instead of evidence.",
  },
  B: {
    id: "B",
    title: "Ending B — Weaponized Truth",
    body: "The Hopo record survives only as targeting doctrine. Evidence created to interrupt violence becomes a manual for beginning it more efficiently.",
    isRestart: true,
  },
  C: {
    id: "C",
    title: "Ending C — The Open Archive",
    body: "The record is public, incomplete, and visibly layered. No authority owns the final explanation, but every future claim can be tested against what survived Hopo.",
    grantsArtifacts: ["VERIFIED_TIMELINE", "LAYERED_ARCHIVE", "OPEN_ARCHIVE_INDEX"],
  },
  D: {
    id: "D",
    title: "Ending D — Hope Protocol",
    body: "The open record, three-artifact proof, and attributed Humans in Space proposal enter community review. Hope is not the answer transmitted—it is the refusal to hide which parts remain choices.",
    grantsArtifacts: ["HUMANS_IN_SPACE_DRAFT", "GOVERNANCE_PACKET", "HOPE_PROTOCOL"],
  },
};

export const EP4_INTERACTIONS: Interaction[] = [
  {
    id: "ep4.archive.intake",
    scene: "EP4_ARCHIVE",
    hotspot: "INTAKE_TERMINAL",
    requires: { has: ["OMEGA_DIRECTIVE", "ELITE_ARTIFACT_LEDGER"], flagsNone: ["ARCHIVE_ADMITTED"] },
    grants: ["CHAIN_OF_CUSTODY"],
    setFlags: ["ARCHIVE_ADMITTED"],
    log: { role: "OMEGA ARCHIVE", text: "Custodian admitted. Your wallet proves access; the chain of custody must prove the record.", kind: "system" },
    once: true,
  },
  { id: "ep4.archive.intake.idle", scene: "EP4_ARCHIVE", hotspot: "INTAKE_TERMINAL", log: { role: "OMEGA ARCHIVE", text: "Access is not authorship. Continue only if every invention remains labeled.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.archive.recorder",
    scene: "EP4_ARCHIVE",
    hotspot: "BUMSEOK_RECORDER",
    requires: { flagsNone: ["TESTIMONY_RECOVERED"] },
    grants: ["FIELD_TESTIMONY"],
    setFlags: ["TESTIMONY_RECOVERED"],
    log: { role: "BUM-SEOK RECORDING", text: "'Write down what we did first. If you erase that, every monster afterward becomes convenient.'", kind: "omega" },
    once: true,
  },
  { id: "ep4.archive.recorder.idle", scene: "EP4_ARCHIVE", hotspot: "BUMSEOK_RECORDER", log: { role: "SYSTEM", text: "The tape ends before Bum-seok says what he believes Kali became.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.archive.cases",
    scene: "EP4_ARCHIVE",
    hotspot: "SEALED_CASES",
    requires: { has: ["CHAIN_OF_CUSTODY"], flagsNone: ["CASES_OPENED"] },
    grants: ["INCIDENT_ARCHIVE"],
    setFlags: ["CASES_OPENED"],
    log: { role: "SYSTEM", text: "The seals align: cattle site, first shot, crash, withdrawal, evacuation, return. Nothing inside proves a complete motive.", kind: "system" },
    once: true,
  },
  { id: "ep4.archive.cases.idle", scene: "EP4_ARCHIVE", hotspot: "SEALED_CASES", log: { role: "SYSTEM", text: "A case without custody is only a story with official stationery.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.archive.redact",
    scene: "EP4_ARCHIVE",
    hotspot: "BURN_ORDER",
    requires: { item: "OMEGA_DIRECTIVE" },
    triggersEnding: "A",
    log: { role: "SYSTEM", text: "The directive enters the furnace. The archive interprets silence as consent to delete.", kind: "danger" },
    once: true,
  },
  { id: "ep4.archive.redact.idle", scene: "EP4_ARCHIVE", hotspot: "BURN_ORDER", log: { role: "SYSTEM", text: "The redaction furnace waits for a custodian to confuse secrecy with safety.", kind: "danger" }, turnCost: 0 },

  {
    id: "ep4.timeline.cattle",
    scene: "EP4_TIMELINE",
    hotspot: "CATTLE_PANEL",
    requires: { item: "INCIDENT_ARCHIVE", flagsNone: ["ORIGIN_REBUILT"] },
    grants: ["TIGER_REBUTTAL"],
    setFlags: ["ORIGIN_REBUILT"],
    log: { role: "SYSTEM", text: "The first error was not a creature. It was the word tiger becoming an order before the wounds were measured.", kind: "system" },
    once: true,
  },
  { id: "ep4.timeline.cattle.idle", scene: "EP4_TIMELINE", hotspot: "CATTLE_PANEL", log: { role: "SYSTEM", text: "The origin panel rejects memory without the physical archive.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.timeline.firstshot",
    scene: "EP4_TIMELINE",
    hotspot: "FIRST_SHOT_PANEL",
    requires: { item: "FIELD_TESTIMONY", has: ["INCIDENT_ARCHIVE"], flagsNone: ["FIRST_SHOT_REBUILT"] },
    grants: ["CAUSALITY_SEQUENCE"],
    setFlags: ["FIRST_SHOT_REBUILT"],
    log: { role: "SYSTEM", text: "Yang-bae's shot moves ahead of the royal search. Human fear remains part of the cause, not a footnote after alien violence.", kind: "danger" },
    once: true,
  },
  { id: "ep4.timeline.firstshot.idle", scene: "EP4_TIMELINE", hotspot: "FIRST_SHOT_PANEL", log: { role: "SYSTEM", text: "A wound can establish sequence, but only testimony connects the hand that fired.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.timeline.contact",
    scene: "EP4_TIMELINE",
    hotspot: "TRUCE_PANEL",
    requires: { item: "ELITE_ARTIFACT_LEDGER", flagsNone: ["CONTACT_REBUILT"] },
    grants: ["CONTACT_OUTCOME"],
    setFlags: ["CONTACT_REBUILT"],
    log: { role: "SYSTEM", text: "The retained artifacts agree on behavior: disarmament and return changed the royal survivors' response without proving forgiveness.", kind: "omega" },
    once: true,
  },
  { id: "ep4.timeline.contact.idle", scene: "EP4_TIMELINE", hotspot: "TRUCE_PANEL", log: { role: "SYSTEM", text: "The ending cannot be reconstructed from a victory claim. It needs surviving objects from the line.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.timeline.sequence",
    scene: "EP4_TIMELINE",
    hotspot: "SEQUENCE_BOARD",
    requires: { item: "CAUSALITY_SEQUENCE", has: ["TIGER_REBUTTAL", "CONTACT_OUTCOME"], flagsAll: ["ORIGIN_REBUILT", "FIRST_SHOT_REBUILT", "CONTACT_REBUILT"], flagsNone: ["TIMELINE_VERIFIED"] },
    grants: ["VERIFIED_TIMELINE"],
    setFlags: ["TIMELINE_VERIFIED"],
    log: { role: "OMEGA ARCHIVE", text: "Sequence accepted: false name, human first shot, alien search, visible restraint. Motive remains partly unreadable.", kind: "system" },
    once: true,
  },
  { id: "ep4.timeline.sequence.idle", scene: "EP4_TIMELINE", hotspot: "SEQUENCE_BOARD", log: { role: "SYSTEM", text: "A complete timeline requires the beginning, the first shot, and the contact outcome.", kind: "default" }, turnCost: 0 },

  {
    id: "ep4.classifier.fact",
    scene: "EP4_CLASSIFIER",
    hotspot: "FACT_TERMINAL",
    requires: { item: "TIGER_REBUTTAL", has: ["VERIFIED_TIMELINE"], flagsNone: ["FACTS_REGISTERED"] },
    grants: ["PROVEN_FACTS"],
    setFlags: ["FACTS_REGISTERED"],
    log: { role: "OMEGA ARCHIVE", text: "PROVEN FACT: the tiger label failed, Kali carried a human projectile, and the vessel was physically damaged.", kind: "system" },
    once: true,
  },
  { id: "ep4.classifier.fact.idle", scene: "EP4_CLASSIFIER", hotspot: "FACT_TERMINAL", log: { role: "SYSTEM", text: "This terminal accepts evidence, not confidence.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.classifier.inference",
    scene: "EP4_CLASSIFIER",
    hotspot: "INFERENCE_TERMINAL",
    requires: { item: "CONTACT_OUTCOME", flagsNone: ["INFERENCES_REGISTERED"] },
    grants: ["SUPPORTED_INFERENCES"],
    setFlags: ["INFERENCES_REGISTERED"],
    log: { role: "OMEGA ARCHIVE", text: "SUPPORTED INFERENCE: the survivors searched for Kali and recognized restraint. No shared language proved their complete intention.", kind: "omega" },
    once: true,
  },
  { id: "ep4.classifier.inference.idle", scene: "EP4_CLASSIFIER", hotspot: "INFERENCE_TERMINAL", log: { role: "SYSTEM", text: "Strong behavior is not the same as translated testimony.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.classifier.proposal",
    scene: "EP4_CLASSIFIER",
    hotspot: "PROPOSAL_TERMINAL",
    requires: { item: "OMEGA_DIRECTIVE", flagsNone: ["PROPOSAL_BOUNDARY_SET"] },
    grants: ["CREATIVE_BOUNDARY"],
    setFlags: ["PROPOSAL_BOUNDARY_SET"],
    log: { role: "OMEGA ARCHIVE", text: "CREATIVE PROPOSAL: every future event must identify its author and may not overwrite the Hopo record.", kind: "system" },
    once: true,
  },
  { id: "ep4.classifier.proposal.idle", scene: "EP4_CLASSIFIER", hotspot: "PROPOSAL_TERMINAL", log: { role: "SYSTEM", text: "A sequel may be bold. It may not pretend that invention was recovered from the field.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.classifier.schema",
    scene: "EP4_CLASSIFIER",
    hotspot: "SCHEMA_CONSOLE",
    requires: { item: "VERIFIED_TIMELINE", has: ["PROVEN_FACTS", "SUPPORTED_INFERENCES", "CREATIVE_BOUNDARY"], flagsAll: ["FACTS_REGISTERED", "INFERENCES_REGISTERED", "PROPOSAL_BOUNDARY_SET"], flagsNone: ["CLASSIFICATION_COMPLETE"] },
    grants: ["LAYERED_ARCHIVE"],
    setFlags: ["CLASSIFICATION_COMPLETE"],
    log: { role: "SYSTEM", text: "Three layers remain separate and linked. Uncertainty is preserved as data instead of erased as weakness.", kind: "system" },
    once: true,
  },
  { id: "ep4.classifier.schema.idle", scene: "EP4_CLASSIFIER", hotspot: "SCHEMA_CONSOLE", log: { role: "SYSTEM", text: "Fact, inference, and proposal must each be signed before the archive can continue.", kind: "default" }, turnCost: 0 },

  {
    id: "ep4.scenario.kali",
    scene: "EP4_SCENARIO",
    hotspot: "KALI_FORK",
    requires: { flagsNone: ["KALI_FORK_DEFINED"] },
    grants: ["KALI_QUESTION"],
    setFlags: ["KALI_FORK_DEFINED"],
    log: { role: "SCENARIO LAB", text: "Kali may recover, remain an absent heir, or survive only through the wound record. The archive confirms none of these futures.", kind: "omega" },
    once: true,
  },
  { id: "ep4.scenario.kali.idle", scene: "EP4_SCENARIO", hotspot: "KALI_FORK", log: { role: "SYSTEM", text: "Kali's future remains a declared story choice.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.scenario.zor",
    scene: "EP4_SCENARIO",
    hotspot: "ZOR_FORK",
    requires: { flagsNone: ["ZOR_FORK_DEFINED"] },
    grants: ["ZOR_QUESTION"],
    setFlags: ["ZOR_FORK_DEFINED"],
    log: { role: "SCENARIO LAB", text: "Zor may forgive, defer judgment, or demand that humans cross into Gertu space as defendants. Hopo proved only that she received the child.", kind: "omega" },
    once: true,
  },
  { id: "ep4.scenario.zor.idle", scene: "EP4_SCENARIO", hotspot: "ZOR_FORK", log: { role: "SYSTEM", text: "Judgment after Hopo belongs to the proposal layer.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.scenario.witness",
    scene: "EP4_SCENARIO",
    hotspot: "WITNESS_FORK",
    requires: { flagsNone: ["WITNESS_FORK_DEFINED"] },
    grants: ["WITNESS_QUESTION"],
    setFlags: ["WITNESS_FORK_DEFINED"],
    log: { role: "SCENARIO LAB", text: "The human witnesses can travel as explorers, defendants, or refugees—but none may become innocent merely by becoming protagonists.", kind: "system" },
    once: true,
  },
  { id: "ep4.scenario.witness.idle", scene: "EP4_SCENARIO", hotspot: "WITNESS_FORK", log: { role: "SYSTEM", text: "A viewpoint character is not an acquittal.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.scenario.mission",
    scene: "EP4_SCENARIO",
    hotspot: "MISSION_TABLE",
    requires: { item: "CREATIVE_BOUNDARY", has: ["LAYERED_ARCHIVE", "KALI_QUESTION", "ZOR_QUESTION", "WITNESS_QUESTION"], flagsAll: ["KALI_FORK_DEFINED", "ZOR_FORK_DEFINED", "WITNESS_FORK_DEFINED"], flagsNone: ["SCENARIO_FRAME_READY"] },
    grants: ["HUMANS_IN_SPACE_DRAFT"],
    setFlags: ["SCENARIO_FRAME_READY"],
    log: { role: "SCENARIO LAB", text: "Draft assembled: humanity enters Gertu space carrying Hopo as testimony, not as a conquest map.", kind: "system" },
    once: true,
  },
  { id: "ep4.scenario.mission.idle", scene: "EP4_SCENARIO", hotspot: "MISSION_TABLE", log: { role: "SYSTEM", text: "The mission needs a Kali question, a Zor question, a human witness role, and a visible creative boundary.", kind: "default" }, turnCost: 0 },

  {
    id: "ep4.governance.artifacts",
    scene: "EP4_GOVERNANCE",
    hotspot: "ARTIFACT_READER",
    requires: { item: "ELITE_ARTIFACT_LEDGER", flagsNone: ["ARTIFACTS_VERIFIED"] },
    grants: ["ARTIFACT_TRIAD"],
    setFlags: ["ARTIFACTS_VERIFIED"],
    log: { role: "OMEGA ARCHIVE", text: "Three-artifact threshold verified. Provenance grants standing to propose, not authority to define canon.", kind: "system" },
    once: true,
  },
  { id: "ep4.governance.artifacts.idle", scene: "EP4_GOVERNANCE", hotspot: "ARTIFACT_READER", log: { role: "SYSTEM", text: "The reader requires the server-verified artifact ledger.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.governance.author",
    scene: "EP4_GOVERNANCE",
    hotspot: "AUTHORSHIP_CONSOLE",
    requires: { item: "HUMANS_IN_SPACE_DRAFT", flagsNone: ["AUTHOR_IDENTIFIED"] },
    grants: ["AUTHORSHIP_RECORD"],
    setFlags: ["AUTHOR_IDENTIFIED"],
    log: { role: "SYSTEM", text: "The proposal is signed by its custodian. Creative responsibility can no longer hide behind a classified seal.", kind: "system" },
    once: true,
  },
  { id: "ep4.governance.author.idle", scene: "EP4_GOVERNANCE", hotspot: "AUTHORSHIP_CONSOLE", log: { role: "SYSTEM", text: "An unsigned future is another rumor waiting to become an order.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.governance.packet",
    scene: "EP4_GOVERNANCE",
    hotspot: "PUBLIC_LEDGER",
    requires: { item: "LAYERED_ARCHIVE", has: ["HUMANS_IN_SPACE_DRAFT", "ARTIFACT_TRIAD", "AUTHORSHIP_RECORD"], flagsAll: ["ARTIFACTS_VERIFIED", "AUTHOR_IDENTIFIED"], flagsNone: ["GOVERNANCE_READY"] },
    grants: ["GOVERNANCE_PACKET"],
    setFlags: ["GOVERNANCE_READY"],
    log: { role: "COMMUNITY RELAY", text: "Packet accepted for public review. Facts remain locked to evidence; the proposed future remains open to votes and revision.", kind: "system" },
    once: true,
  },
  { id: "ep4.governance.packet.idle", scene: "EP4_GOVERNANCE", hotspot: "PUBLIC_LEDGER", log: { role: "SYSTEM", text: "The ledger needs provenance, authorship, the layered archive, and a scenario draft.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.governance.weaponize",
    scene: "EP4_GOVERNANCE",
    hotspot: "MILITARY_UPLINK",
    requires: { item: "GOVERNANCE_PACKET" },
    triggersEnding: "B",
    log: { role: "RESTRICTED UPLINK", text: "Behavioral inference converted to targeting doctrine. Uncertainty removed. Counter-contact weapon model compiling.", kind: "danger" },
    once: true,
  },
  { id: "ep4.governance.weaponize.idle", scene: "EP4_GOVERNANCE", hotspot: "MILITARY_UPLINK", log: { role: "SYSTEM", text: "The uplink offers certainty by deleting every reason the archive was kept layered.", kind: "danger" }, turnCost: 0 },

  {
    id: "ep4.transmission.publish",
    scene: "EP4_TRANSMISSION",
    hotspot: "PUBLIC_MIRROR",
    requires: { item: "LAYERED_ARCHIVE", has: ["GOVERNANCE_PACKET"], flagsAll: ["GOVERNANCE_READY", "CLASSIFICATION_COMPLETE"], flagsNone: ["ARCHIVE_PUBLIC"] },
    grants: ["OPEN_ARCHIVE_INDEX"],
    setFlags: ["ARCHIVE_PUBLIC"],
    log: { role: "OMEGA RELAY", text: "Public mirror active. Every fact links to evidence; every inference exposes its uncertainty; every invention exposes its author.", kind: "system" },
    once: true,
  },
  { id: "ep4.transmission.publish.idle", scene: "EP4_TRANSMISSION", hotspot: "PUBLIC_MIRROR", log: { role: "SYSTEM", text: "Nothing can be called open until the layered archive and governance packet agree.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.transmission.archive",
    scene: "EP4_TRANSMISSION",
    hotspot: "ARCHIVE_EXIT",
    requires: { item: "OPEN_ARCHIVE_INDEX", flagsAll: ["ARCHIVE_PUBLIC"] },
    triggersEnding: "C",
    log: { role: "OMEGA RELAY", text: "The Hopo archive opens without a final answer. The community inherits evidence and the duty to keep disagreement visible.", kind: "omega" },
    once: true,
  },
  { id: "ep4.transmission.archive.idle", scene: "EP4_TRANSMISSION", hotspot: "ARCHIVE_EXIT", log: { role: "SYSTEM", text: "Publish the layered archive before closing the protocol.", kind: "default" }, turnCost: 0 },
  {
    id: "ep4.transmission.hope",
    scene: "EP4_TRANSMISSION",
    hotspot: "OMEGA_RELAY",
    requires: { item: "GOVERNANCE_PACKET", has: ["OPEN_ARCHIVE_INDEX", "HUMANS_IN_SPACE_DRAFT", "ARTIFACT_TRIAD"], flagsAll: ["ARCHIVE_PUBLIC", "ARTIFACTS_VERIFIED", "AUTHOR_IDENTIFIED"] },
    grants: ["HOPE_PROTOCOL"],
    setFlags: ["HOPE_PROTOCOL_SUBMITTED"],
    triggersEnding: "D",
    log: { role: "OMEGA RELAY", text: "HOPE PROTOCOL TRANSMITTED. The archive remains evidence. The future remains a proposal. The next first shot has not happened yet.", kind: "omega" },
    once: true,
  },
  { id: "ep4.transmission.hope.idle", scene: "EP4_TRANSMISSION", hotspot: "OMEGA_RELAY", log: { role: "SYSTEM", text: "The relay requires an open archive, verified artifacts, attributed authorship, and the complete governance packet.", kind: "default" }, turnCost: 0 },
  { id: "ep4.transmission.signal", scene: "EP4_TRANSMISSION", hotspot: "SIGNAL_WINDOW", log: { role: "UNKNOWN SIGNAL", text: "No translation arrives. A pulse repeats at the interval between Yang-bae's shot and Kali's return.", kind: "omega" }, turnCost: 0 },
];

export const EP4_INITIAL_LOGS = [
  { turn: 1, role: "SYSTEM", text: "EPISODE 4 · OMEGA PROTOCOL", kind: "system" as const },
  { turn: 1, role: "OMEGA ARCHIVE", text: "The Hopo record survived. Its labels did not.", kind: "omega" as const },
  { turn: 1, role: "BUM-SEOK RECORDING", text: "'If this reaches somebody after us, begin with what we did first.'", kind: "voice" as const },
  { turn: 1, role: "SYSTEM", text: "OBJECTIVE · Rebuild the causal record, separate fact from invention, and decide how humanity will carry Hopo forward.", kind: "danger" as const },
];

export const EPISODE_4: GameDefinition = {
  id: "ep4",
  number: 4,
  version: 1,
  title: "Omega Protocol",
  headerLabel: "OMEGA ARCHIVE · EPISODE 4",
  maxTurns: EP4_MAX_TURNS,
  storageKey: "nahope_game_ep4_v1",
  scenes: EP4_SCENES,
  sceneOrder: ["EP4_ARCHIVE", "EP4_TIMELINE", "EP4_CLASSIFIER", "EP4_SCENARIO", "EP4_GOVERNANCE", "EP4_TRANSMISSION"],
  items: EP4_ITEMS,
  interactions: EP4_INTERACTIONS,
  endings: EP4_ENDINGS,
  initialScene: "EP4_ARCHIVE" as SceneId,
  initialLogs: EP4_INITIAL_LOGS,
  initialInventory: ["OMEGA_DIRECTIVE", "ELITE_ARTIFACT_LEDGER"],
  waitText: "You wait. The archive's deletion clock advances while certainty becomes easier to manufacture.",
  successfulEndings: ["C", "D"],
  caseRecord: {
    title: "Omega Protocol · Archive Schema",
    rows: [
      { label: "Causal record", text: "false tiger label → human first shot → royal search → visible restraint", revealFlag: "TIMELINE_VERIFIED" },
      { label: "Proven fact", text: "physical evidence and converging testimony only", revealFlag: "FACTS_REGISTERED" },
      { label: "Inference", text: "behavioral reading retained with uncertainty", revealFlag: "INFERENCES_REGISTERED" },
      { label: "Proposal", text: "Humans in Space choices attributed to the player", revealFlag: "SCENARIO_FRAME_READY" },
      { label: "Governance", text: "artifact provenance, authorship, and public review attached", revealFlag: "GOVERNANCE_READY" },
    ],
    notes: [
      { text: "archive principle · uncertainty is evidence of honesty, not a defect to redact", revealFlag: "CLASSIFICATION_COMPLETE" },
      { text: "hope principle · the next first shot remains a choice", revealFlag: "HOPE_PROTOCOL_SUBMITTED" },
    ],
  },
};
