export const GAME_KO: Record<string, string> = {
  // Episode 1 metadata, scenes, and hotspots
  "The Hopo Tiger": "호포의 호랑이",
  "HOPO PORT · DAY OF INCIDENT": "호포항 · 사건 당일",
  "Hopo Substation · Duty Room": "호포 파출소 · 당직실",
  "Daylight on old paperwork. Both the telephone and police radio are silent.": "낡은 서류 위로 낮빛이 든다. 전화와 경찰 무전기는 모두 침묵하고 있다.",
  "Duty Log": "당직 일지",
  "Evidence Cabinet": "증거물 보관함",
  "Service Carbine": "업무용 카빈",
  "Telephone": "전화기",
  "Police Radio": "경찰 무전기",
  "Hopo Substation · Equipment Room": "호포 파출소 · 장비실",
  "Survey tools, reserve ammunition, and yesterday's maintenance sheet.": "측량 도구와 예비 탄약, 어제 작성된 정비 기록지가 놓여 있다.",
  "Equipment Locker": "장비 사물함",
  "Maintenance Sheet": "정비 기록지",
  "Field Shelf": "현장 장비 선반",
  "Hopo Substation · Front Yard": "호포 파출소 · 앞마당",
  "Sung-gi and the village hunters wait beside the patrol car, already calling it a tiger.": "성기와 마을 사냥꾼들이 순찰차 옆에서 기다린다. 그들은 벌써 그것을 호랑이라고 부른다.",
  "Radio Antenna": "무전 안테나",
  "Sung-gi · Hunter": "성기 · 사냥꾼",
  "Patrol Car": "순찰차",
  "Hopo Fields · Cattle Site": "호포 들판 · 소 사체 현장",
  "A cow lies opened in broad daylight. Nothing has fed on it.": "한낮의 들판에 소 한 마리가 찢긴 채 놓여 있다. 그러나 아무것도 사체를 먹지 않았다.",
  "Cattle Carcass": "소 사체",
  "Compressed Soil": "눌린 흙",
  "Pine Ridge": "소나무 능선",
  "Pine Ridge · Search Line": "소나무 능선 · 수색선",
  "Broken branches rise above a man's head. The tracks turn back toward the village.": "사람 머리보다 높은 곳의 가지가 부러져 있다. 흔적은 마을 쪽으로 되돌아간다.",
  "Deep Tracks": "깊게 팬 흔적",
  "Ridge Lookout": "능선 전망 지점",
  "Descent to Hopo": "호포로 내려가는 길",
  "Hopo Port · Ruined Main Road": "호포항 · 파괴된 큰길",
  "Vehicles and walls lie wrecked in daylight. The wounded Bamigir is still moving.": "대낮에 차량과 벽이 부서져 널려 있다. 부상당한 바미기르는 아직 움직인다.",
  "Impact Wreckage": "충돌 잔해",
  "Wounded Bamigir": "부상당한 바미기르",

  // Episode 1 items
  "Equipment Cabinet Key": "장비 보관함 열쇠",
  "Tagged HOPO SUBSTATION. Returned after every shift.": "'호포 파출소' 꼬리표가 달렸다. 근무가 끝날 때마다 반납한다.",
  "Resident Duty Roster": "주민 당직 명부",
  "Households, elders, and the eight reservists currently in Hopo Port.": "호포항의 가구와 노인, 현재 마을에 있는 예비군 여덟 명의 명단.",
  "Police Evidence Camera": "경찰 증거 사진기",
  "One roll loaded. Photographs before conclusions.": "필름 한 통이 들어 있다. 결론보다 사진이 먼저다.",
  "Field Measuring Rule": "현장 측정자",
  "A folding rule marked in centimeters.": "센티미터 눈금이 새겨진 접이식 자.",
  "Plaster Evidence Kit": "석고 증거 채취함",
  "Canvas bag with plaster, water vial, and specimen envelopes.": "석고와 물병, 표본 봉투가 든 캔버스 가방.",
  "Predator Field Guide": "포식동물 현장 도감",
  "Field notes compare wound spacing, prints, and feeding behavior.": "상처 간격과 발자국, 섭식 행동을 비교한 현장 기록.",
  "Carbine Ammunition": "카빈 탄약",
  "Live rounds. A conclusion made of brass and lead.": "실탄. 황동과 납으로 내려 버리는 결론.",
  "Field Binoculars": "야전 쌍안경",
  "Military surplus. The right lens is chipped.": "군용 불용품. 오른쪽 렌즈가 깨져 있다.",
  "Carcass Photograph": "소 사체 사진",
  "The hide is raked open, but no flesh has been eaten.": "가죽은 갈라졌지만 살점은 먹히지 않았다.",
  "Wound Measurements": "상처 측정 기록",
  "Parallel wounds wider and higher than the field guide permits.": "도감의 어떤 사례보다 넓고 높은 평행 상처.",
  "Unknown Track Cast": "미확인 흔적 석고본",
  "A partial impression too deep for a tiger of any recorded size.": "기록상 어떤 호랑이도 남길 수 없을 만큼 깊은 부분 흔적.",
  "Bamigir Encounter Photograph": "바미기르 조우 사진",
  "The wounded sentry is crying. Bum-seok's rifle remains lowered.": "부상당한 보초가 울고 있다. 범석의 소총은 내려가 있다.",
  "Unknown Subject Case File": "미확인 대상 사건철",
  "Official classification: not a tiger, motive unknown, threat moving toward Hopo Port.": "공식 분류: 호랑이 아님. 동기 불명. 위협 대상은 호포항으로 이동 중.",
  "Unfired Cartridge": "발사하지 않은 탄환",
  "Bum-seok saw grief in the unknown subject and lowered the rifle.": "범석은 미확인 대상의 슬픔을 보고 소총을 내렸다.",

  // Episode 1 endings
  "Ending A — The Tiger Hunt": "엔딩 A — 호랑이 사냥",
  "The report says tiger. Sung-gi leads the young men into the forest with live ammunition. By the time Hopo learns the word was wrong, they have become the hunted.": "보고서에는 호랑이라고 적힌다. 성기는 실탄을 든 청년들을 숲으로 이끈다. 호포가 그 단어가 틀렸음을 알았을 때, 그들은 이미 사냥감이 되어 있다.",
  "Ending B — Premature Fire": "엔딩 B — 성급한 발포",
  "Bum-seok fires before identifying the subject. The report becomes a weapon, and Hopo loses its only chance to understand why the wounded creature was crying.": "범석은 대상을 확인하기 전에 발포한다. 보고서는 무기가 되고, 호포는 부상당한 존재가 왜 울고 있었는지 이해할 유일한 기회를 잃는다.",
  "Ending C — Unknown Subject": "엔딩 C — 미확인 대상",
  "The case file rejects the tiger theory, the elders are marked for evacuation, and Sung-gi's hunt is delayed. Hopo has not understood the visitor, but it has stopped pretending that it has.": "사건철은 호랑이설을 기각하고 노인들을 대피 명단에 올린다. 성기의 사냥은 미뤄진다. 호포는 방문자를 이해하지 못했지만, 이해한 척하는 일은 멈췄다.",
  "Ending D — The Creature Was Crying": "엔딩 D — 그 존재는 울고 있었다",
  "Bum-seok records the wounded sentry's tears and the shot he chose not to fire. The evidence cannot prove innocence, but it destroys the comforting lie that Hopo faced a mindless beast.": "범석은 부상당한 보초의 눈물과 자신이 쏘지 않기로 한 한 발을 기록한다. 그 증거는 결백을 입증하지 못하지만, 호포가 이성 없는 짐승과 맞섰다는 안락한 거짓말은 무너뜨린다.",

  // Episode 1 logs
  "'Strike tiger from the report. Unknown subject. Protect the elders and keep Sung-gi out of that forest.'": "'보고서에서 호랑이를 지워. 미확인 대상으로 기록해. 노인들을 보호하고 성기가 숲에 들어가지 못하게 해.'",
  "Eight reservists are away at the wildfire. The roster leaves mostly elders in Hopo. The cabinet key is clipped inside.": "예비군 여덟 명은 산불 진화에 투입됐다. 호포에는 대부분 노인만 남았다. 명부 안쪽에 보관함 열쇠가 끼워져 있다.",
  "The blank incident line waits for a noun. Tiger is only Sung-gi's guess.": "비어 있는 사건명 칸이 명사를 기다린다. 호랑이는 성기의 추측일 뿐이다.",
  "Evidence camera, one roll. The label says: photograph before moving anything.": "증거 사진기와 필름 한 통. 꼬리표에는 '무엇이든 옮기기 전에 촬영할 것'이라고 적혀 있다.",
  "Locked. The duty officer keeps the key with the roster.": "잠겨 있다. 당직자는 명부와 함께 열쇠를 보관한다.",
  "The evidence cabinet is empty.": "증거물 보관함은 비어 있다.",
  "A round chambers. Movement crosses the window. Bum-seok fires before the shape has a name; the shot disappears into Hopo and the pursuit begins.": "탄환이 약실에 들어간다. 창밖으로 무언가 움직인다. 범석은 형체에 이름이 붙기 전에 발포한다. 총성은 호포 안으로 사라지고 추격이 시작된다.",
  "'A dead cow is evidence. It is not permission to shoot the next thing that moves.'": "'죽은 소는 증거야. 다음에 움직이는 것을 쏴도 된다는 허가는 아니야.'",
  "No dial tone. The line is intact inside the room; the failure lies beyond the substation.": "발신음이 없다. 방 안의 선은 멀쩡하다. 고장은 파출소 바깥에 있다.",
  "The receiver carries only the room's own silence.": "수화기에서는 방 안의 침묵만 되돌아온다.",
  "The set powers on. No carrier, no district station, no wildfire crews. Communications are severed beyond Hopo.": "무전기의 전원은 켜진다. 반송파도, 지서도, 산불 진화대도 잡히지 않는다. 통신은 호포 바깥에서 끊겼다.",
  "Dead air. Not static—absence.": "죽은 공기. 잡음이 아니라 부재다.",
  "A measuring rule, plaster kit, and sealed carbine ammunition. Observation and force stored on the same shelf.": "측정자와 석고 채취함, 밀봉된 카빈 탄약. 관찰과 폭력이 같은 선반에 보관되어 있다.",
  "The equipment locker is locked.": "장비 사물함은 잠겨 있다.",
  "Only empty hooks remain.": "빈 고리만 남아 있다.",
  "Maintenance sheet: radio feed line and antenna tested yesterday. Both passed.": "정비 기록: 무전 급전선과 안테나를 어제 점검함. 둘 다 정상.",
  "The sheet is pinned behind the locker door.": "기록지가 사물함 문 뒤에 꽂혀 있다.",
  "A predator guide and chipped binoculars. The tiger diagrams are smaller than Sung-gi's story.": "포식동물 도감과 렌즈가 깨진 쌍안경. 도감 속 호랑이는 성기의 이야기보다 작다.",
  "Dust outlines the gear you removed.": "꺼낸 장비의 윤곽만 먼지 위에 남아 있다.",
  "'Tiger, bear, whatever. We have rifles.' Sung-gi takes the ammunition and leads the young men into the pines.": "'호랑이든 곰이든 상관없어. 우리에겐 총이 있어.' 성기가 탄약을 받아 청년들을 소나무 숲으로 이끈다.",
  "'Fine. It clawed the cow, but it didn't eat a bite. We'll wait until you see it.'": "'좋아. 소를 할퀴었지만 한 입도 먹지 않았어. 형이 직접 볼 때까지 기다리지.'",
  "'Something tore up a cow by the millet field. Looks like a tiger, but the marks are too high.'": "'조밭 옆에서 뭔가가 소를 찢어 놨어. 호랑이 같지만 흔적이 너무 높아.'",
  "'Bring me a fact, hyung. Then decide what we are hunting.'": "'사실 하나만 가져와, 형. 그다음 우리가 뭘 사냥하는지 정해.'",
  "The antenna and feed line are undamaged. Hopo is isolated, but the substation equipment did not cause it.": "안테나와 급전선에는 손상이 없다. 호포는 고립됐지만 파출소 장비가 원인은 아니다.",
  "The mast is upright. Check the set and its maintenance history before blaming the hardware.": "안테나는 똑바로 서 있다. 장비를 탓하기 전에 무전기와 정비 기록부터 확인해야 한다.",
  "'Circle the elder households. No siren. Move everyone to the concrete clinic before panic names this thing for us.'": "'노인 가구부터 돌아. 사이렌은 울리지 마. 공포가 저것에 이름을 붙이기 전에 모두 콘크리트 보건소로 옮겨.'",
  "The patrol car can carry a warning or spread a panic. It needs a plan and a roster.": "순찰차는 경고를 전할 수도, 공포를 퍼뜨릴 수도 있다. 계획과 명부가 필요하다.",
  "The shutter records parallel wounds and an untouched carcass. Whatever killed the cow did not feed.": "셔터가 평행한 상처와 먹히지 않은 사체를 기록한다. 소를 죽인 것은 먹이를 먹지 않았다.",
  "The wound span exceeds the largest tiger diagram. The highest strike landed above a standing man's shoulder.": "상처 간격은 도감 속 가장 큰 호랑이보다 넓다. 가장 높은 타격점은 선 사람의 어깨보다 위다.",
  "'It did not feed. Wrong height, wrong span. Write unknown subject—not tiger.'": "'먹지 않았어. 높이도, 간격도 틀려. 호랑이가 아니라 미확인 대상으로 적어.'",
  "The cow was killed with overwhelming force. A guess will not explain why it was left uneaten.": "소는 압도적인 힘으로 죽었다. 추측만으로는 왜 먹히지 않은 채 남았는지 설명할 수 없다.",
  "The plaster hardens around a partial track. Its depth suggests a mass no local predator could carry.": "석고가 부분 흔적을 감싸 굳는다. 깊이로 보아 이 지역의 어떤 포식자도 가질 수 없는 질량이다.",
  "Compressed earth, not a clean print. Preserve it before comparing it.": "선명한 발자국이 아니라 눌린 흙이다. 비교하기 전에 보존해야 한다.",
  "You enter the pines only after striking tiger from the report.": "보고서에서 호랑이를 지운 뒤에야 소나무 숲으로 들어간다.",
  "Do not send another armed man into the trees until the carcass contradicts the tiger story.": "사체가 호랑이설을 반박하기 전까지 무장한 사람을 숲에 더 보내서는 안 된다.",
  "The field impression matches. The stride crosses broken branches at human head height, then turns back toward Hopo.": "들판의 흔적과 일치한다. 보폭은 사람 머리 높이의 부러진 가지를 지나 호포 쪽으로 되돌아간다.",
  "Deep, incomplete impressions. A cast from the field would establish whether the same subject made them.": "깊지만 불완전한 흔적. 들판의 석고본과 비교하면 같은 대상이 남겼는지 알 수 있다.",
  "Bum-seok fires at the moving outline before identifying it. The subject vanishes into Hopo, and fear becomes the only evidence left.": "범석은 움직이는 윤곽을 확인하기 전에 발포한다. 대상은 호포 안으로 사라지고 공포만이 유일한 증거로 남는다.",
  "An immense upright figure crosses the road below. It is moving toward Hopo, not hiding in the forest.": "거대한 직립 형체가 아래 도로를 가로지른다. 숲에 숨는 것이 아니라 호포로 향하고 있다.",
  "The subject turns. There is grief in its face. Bum-seok lowers the rifle before fear can become evidence.": "대상이 돌아본다. 얼굴에 슬픔이 있다. 공포가 증거가 되기 전에 범석은 소총을 내린다.",
  "The ridge overlooks too much country for the naked eye. Tracks first, then distance.": "맨눈으로 보기에는 능선 아래가 너무 넓다. 흔적을 먼저, 거리는 그다음이다.",
  "You follow the subject's route down to Hopo's ruined main road.": "대상의 경로를 따라 호포의 파괴된 큰길로 내려간다.",
  "Something is below, but pursuing it before deciding whether to fire would only repeat the mistake.": "아래에 무언가 있다. 쏠지 말지 결정하기도 전에 추격하면 같은 실수를 되풀이할 뿐이다.",
  "The reach and impact height match the cattle-site measurements. The figure from the ridge has entered Hopo.": "도달 거리와 충돌 높이가 소 사체 현장의 측정값과 일치한다. 능선의 형체가 호포에 들어왔다.",
  "Metal and concrete failed above a man's reach. Compare the damage with the cattle-site measurements.": "사람 손이 닿지 않는 높이에서 금속과 콘크리트가 부서졌다. 소 사체 현장의 측정값과 비교해야 한다.",
  "Through the lens, the wounded sentry is crying. The photograph explains neither motive nor innocence; it only records that the 'beast' can grieve.": "렌즈 너머로 부상당한 보초가 울고 있다. 사진은 동기도 결백도 설명하지 않는다. 다만 그 '짐승'이 슬퍼할 수 있음을 기록한다.",
  "Bum-seok seals the photograph with the unfired cartridge. His report begins: 'The creature was crying. I could not pull the trigger.'": "범석은 발사하지 않은 탄환과 사진을 함께 봉인한다. 보고서는 이렇게 시작한다. '그 존재는 울고 있었다. 나는 방아쇠를 당길 수 없었다.'",
  "The towering wounded figure watches Hopo through tears. Observation must come before judgment.": "거대한 부상자가 눈물 너머로 호포를 바라본다. 판단보다 관찰이 먼저다.",
  "HOPO PORT · DAY OF INCIDENT · 10:17": "호포항 · 사건 당일 · 10:17",
  "'Hyung, something tore up a cow by the millet field. The others are calling it a tiger.'": "'형, 조밭 옆에서 뭔가가 소를 찢어 놨어. 사람들은 호랑이라고 해.'",
  "'Do not name it before I see it. Nobody goes into the forest yet.'": "'내가 보기 전에는 이름 붙이지 마. 아직 아무도 숲에 들어가지 않는다.'",
  "Move between locations · equip evidence · select hotspots to investigate.": "장소를 이동하고 · 증거를 장착하고 · 조사 지점을 선택하십시오.",
  "You wait. The dead radio stays silent while the village grows louder.": "기다린다. 죽은 무전기는 침묵하고 마을의 소음은 커져 간다.",
  "Incident Record · Hopo Port": "사건 기록 · 호포항",
  "Initial report — cattle carcass": "최초 보고 — 소 사체",
  "claw trauma; carcass left uneaten": "발톱 형태 외상; 사체는 먹히지 않음",
  "Classification": "분류",
  "NOT A TIGER · unknown subject": "호랑이 아님 · 미확인 대상",
  "Communications": "통신",
  "telephone and police radio severed beyond local hardware": "전화와 경찰 무전이 지역 장비 바깥에서 단절됨",
  "Search direction": "수색 방향",
  "oversized tracks return toward Hopo Port": "대형 흔적이 호포항 방향으로 되돌아감",
  "margin note · subject displayed grief; fire withheld": "여백 메모 · 대상이 슬픔을 보임; 발포 보류",
  "encounter note · tears visible; intent remains unknown": "조우 메모 · 눈물 확인; 의도는 불명",

  // Episode 2 metadata, scenes, and hotspots
  "The Hunt Reverses": "뒤집힌 사냥",
  "HOPO PORT · MOUNTAIN SEARCH": "호포항 · 산악 수색",
  "Human Dust": "인간의 먼지",
  "HOPO INCIDENT · EPISODE 3": "호포 사건 · 에피소드 3",
  "Omega Protocol": "오메가 프로토콜",
  "OMEGA ARCHIVE · EPISODE 4": "오메가 기록보관소 · 에피소드 4",
  "The civilian corridor is classified. Complete the mountain case and verify the required wallet balance to enter.": "민간인 통로는 기밀로 분류되었습니다. 산악 사건을 완료하고 필요한 지갑 잔액을 확인해야 입장할 수 있습니다.",
  "The final archive requires an Episode 3 clear, three retained Hopo artifacts, and server-verified Elite Defender holdings.": "최종 기록보관소는 에피소드 3 클리어, 호포 희귀 유물 3개 보유, 서버로 확인된 엘리트 방어자 잔액이 필요합니다.",
  "Hopo Port · Triage Line": "호포항 · 응급 처치선",
  "Bamigir is down. Sung-ae treats the living while Sung-ki prepares to sweep the mountain.": "바미기르가 쓰러졌다. 성애는 생존자를 치료하고 성기는 산악 수색을 준비한다.",
  "Search Command Post": "수색 지휘소",
  "Sung-ae · Field Triage": "성애 · 현장 응급 처치",
  "Bamigir Aftermath": "바미기르 습격 현장",
  "Hunter Ammunition": "사냥꾼 탄약",
  "Hopo Port · Yang-bae's Workshop": "호포항 · 양배의 작업실",
  "Unfinished mannequins face a humming cold-room door. Yang-bae will not meet your eyes.": "완성되지 않은 마네킹들이 윙윙대는 냉동실 문을 바라본다. 양배는 시선을 마주치지 않는다.",
  "Mannequin Row": "마네킹 열",
  "Locked Cold Room": "잠긴 냉동실",
  "Yang-bae · Carpenter": "양배 · 목수",
  "Carpenter's Delivery Map": "목수의 배달 지도",
  "Workshop · Cold Room": "작업실 · 냉동실",
  "The compressor drowns the village outside. Something small lies beneath a canvas sheet.": "압축기 소리가 바깥 마을의 소음을 삼킨다. 캔버스 천 아래에 작은 무언가가 누워 있다.",
  "Covered Small Body": "천에 덮인 작은 몸",
  "Frost beneath the Rack": "받침대 아래의 서리",
  "Cold-room Compressor": "냉동실 압축기",
  "Mountain Trail · Hunter Line": "산길 · 사냥꾼 수색선",
  "Sung-ki's party moves uphill. Yang-bae knows this path better than he admitted.": "성기 일행이 산을 오른다. 양배는 인정한 것보다 이 길을 훨씬 잘 안다.",
  "Silver-grey Trail Mud": "은회색 산길 진흙",
  "Overlapping Tracks": "겹쳐진 흔적",
  "Sung-ki's Hunters": "성기의 사냥꾼들",
  "Glint beyond the Ridge": "능선 너머의 섬광",
  "Pine Basin · Silver Wreck": "소나무 분지 · 은빛 잔해",
  "A silver vessel has torn a trench through the forest. Tracks lead away from its ruptured hull.": "은빛 선체가 숲을 가르며 골을 팠다. 파열된 선체에서 여러 흔적이 밖으로 이어진다.",
  "Ruptured Silver Hull": "파열된 은빛 선체",
  "Tracks from the Wreck": "잔해에서 나온 흔적",
  "Child-sized Compartment": "아이 크기의 격실",
  "Voices below the Basin": "분지 아래의 목소리",
  "Deep Forest · Encirclement": "깊은 숲 · 포위",
  "Three different figures surround the hunters. They speak to one another, but none has struck first.": "서로 다른 세 형체가 사냥꾼들을 둘러싼다. 그들은 서로 말하지만 누구도 먼저 공격하지 않았다.",
  "Ma'veyyo · Royal Guard": "마베요 · 왕실 경호원",
  "Zor and Aydobor": "조르와 아이도보르",
  "Hunter Withdrawal Line": "사냥꾼 철수로",

  // Episode 2 items
  "Bum-seok's Case File": "범석의 사건철",
  "Not a tiger. The first wounded subject cried before it died.": "호랑이가 아니다. 처음 다친 대상은 죽기 전에 울었다.",
  "The remaining frames must establish cause, not merely damage.": "남은 필름은 피해가 아니라 원인을 입증해야 한다.",
  "Mountain Search Map": "산악 수색 지도",
  "Sung-ki's sweep line and every known road out of the basin.": "성기의 수색선과 분지 밖으로 이어지는 모든 확인된 길.",
  "Sung-ae's Trauma Kit": "성애의 응급 처치함",
  "Bandages, forceps, and a field card for distinguishing wounds.": "붕대와 겸자, 상처를 구분하는 현장 판정표.",
  "Ceasefire Flare": "정전 신호탄",
  "A red signal Sung-ae orders the hunters not to fire through.": "성애가 사냥꾼들에게 이 붉은 신호 너머로 쏘지 말라고 명령했다.",
  "A fast answer to a question nobody has understood.": "아무도 이해하지 못한 질문에 내놓는 성급한 답.",
  "Cold-room Key": "냉동실 열쇠",
  "Found behind the blank face of one of Yang-bae's mannequins.": "양배의 마네킹 하나, 텅 빈 얼굴 뒤에서 발견됐다.",
  "Mud-stained Mannequin Tag": "진흙 묻은 마네킹 꼬리표",
  "Pine resin and silver-grey soil cling to the carpenter's inventory tag.": "목수의 재고 꼬리표에 송진과 은회색 흙이 붙어 있다.",
  "Kali Evidence Photograph": "칼리 증거 사진",
  "A small childlike body in a freezer, killed by a human bullet.": "냉동실에 놓인 아이 같은 작은 몸. 인간의 탄환에 맞아 죽었다.",
  "Spent Hunting Casing": "발사된 사냥탄 탄피",
  "The firing-pin mark matches Yang-bae's hunting gun.": "공이 자국이 양배의 사냥총과 일치한다.",
  "Yang-bae's Statement": "양배의 진술서",
  "He saw something small in the forest, fired without warning, and hid it in the freezer.": "그는 숲에서 작은 존재를 보고 경고 없이 발포한 뒤 냉동실에 숨겼다.",
  "Multiple-subject Track Sketch": "다중 대상 흔적 스케치",
  "Several anatomies crossed the same trail from one impact basin.": "서로 다른 여러 신체 구조가 하나의 충돌 분지에서 같은 길을 지나갔다.",
  "Silver Hull Fragment": "은빛 선체 파편",
  "Metal folded outward by a crash, not arranged for an invasion landing.": "침공 착륙이 아니라 추락 충격으로 바깥쪽으로 접힌 금속.",
  "First-shot Causality Report": "최초 발포 인과 보고서",
  "The royal survivors searched for Kali; Yang-bae's bullet came before their encirclement.": "왕실 생존자들은 칼리를 찾았다. 양배의 탄환이 그들의 포위보다 먼저였다.",
  "Forest Withdrawal Route": "숲 철수로",
  "A flare-marked path that extracts the hunters without firing through the encirclement.": "포위망에 발포하지 않고 사냥꾼들을 빼내는 신호탄 표시 경로.",

  // Episode 2 endings
  "Ending A — The Hunt Reverses": "엔딩 A — 뒤집힌 사냥",
  "The search line advances under the old tiger story. In the mountain, Sung-ki's hunters discover that they were never the only ones following tracks.": "수색대는 낡은 호랑이 이야기를 믿고 전진한다. 산속에서 성기의 사냥꾼들은 흔적을 쫓는 존재가 자신들뿐이 아니었음을 깨닫는다.",
  "Ending B — First Shot, Again": "엔딩 B — 다시, 최초의 발포",
  "Another human weapon answers a voice nobody understands. The royal survivors stop searching and Ma'veyyo begins the pursuit.": "아무도 이해하지 못한 목소리에 또다시 인간의 무기가 답한다. 왕실 생존자들은 수색을 멈추고 마베요는 추격을 시작한다.",
  "Ending C — Break the Encirclement": "엔딩 C — 포위망 이탈",
  "The flare holds the firing line long enough to withdraw Sung-ki's hunters. Hopo survives the encounter knowing the vessel crashed and the strangers were searching for a child.": "신호탄은 성기의 사냥꾼들이 철수할 때까지 발포선을 붙든다. 호포는 선체가 추락했고 낯선 이들이 한 아이를 찾고 있었다는 사실을 안 채 조우에서 살아남는다.",
  "Ending D — The Child in the Freezer": "엔딩 D — 냉동실의 아이",
  "Yang-bae's statement, Kali's photograph, and the wreck establish the first causal chain Hopo cannot bear to read: a human bullet preceded the royal survivors' violence.": "양배의 진술, 칼리의 사진, 추락 잔해가 호포가 차마 읽기 힘든 최초의 인과를 확정한다. 왕실 생존자들의 폭력보다 인간의 탄환이 먼저였다.",

  // Episode 2 logs
  "The mountain sweep begins with a map and an evidence camera. No one fires at a silhouette.": "산악 수색은 지도와 증거 사진기로 시작한다. 누구도 윤곽만 보고 발포하지 않는다.",
  "Sung-ki's search line is marked, but the reason for the visitors' movement is still blank.": "성기의 수색선은 표시됐지만 방문자들이 움직인 이유는 아직 비어 있다.",
  "'I will keep the wounded breathing. Take the red flare—if it burns, every muzzle stays down.'": "'부상자들은 내가 살려 둘게. 붉은 신호탄을 가져가. 저게 타오르면 모든 총구를 내려.'",
  "'The village is not safe. It is only between attacks.'": "'마을은 안전한 게 아니야. 그저 공격과 공격 사이에 있을 뿐이야.'",
  "The frame records impact wounds, a missing leg, and tear tracks. Rage explains the damage no better than tiger did.": "사진에는 충격 상처와 사라진 다리, 눈물 자국이 남는다. 분노라는 말도 호랑이라는 말만큼이나 이 피해를 설명하지 못한다.",
  "'It was crying before the truck. Write that down before we decide what it was.'": "'트럭이 덮치기 전에 울고 있었어. 그게 무엇인지 정하기 전에 그 사실부터 적어.'",
  "Live hunting rounds. Useful against a threat; disastrous as a substitute for identifying one.": "사냥용 실탄. 위협에는 유용하지만, 대상을 확인하는 일을 대신하면 재앙이 된다.",
  "The empty crate is lighter than the decision it created.": "빈 탄약 상자는 그것이 만든 결정보다 가볍다.",
  "A cold-room key is taped behind a mannequin face. Its stock tag carries pine resin and silver-grey mountain soil.": "마네킹 얼굴 뒤에 냉동실 열쇠가 붙어 있다. 재고 꼬리표에는 송진과 은회색 산흙이 묻었다.",
  "Blank human faces in rows. Yang-bae has practiced making bodies look harmless.": "텅 빈 인간의 얼굴이 줄지어 있다. 양배는 몸을 무해해 보이게 만드는 일을 반복해 왔다.",
  "The lock opens. Cold air carries the smell of pine soil and gun oil.": "자물쇠가 열린다. 찬 공기에 소나무 흙과 총기 기름 냄새가 실려 온다.",
  "The cold room is locked. Yang-bae says the key was lost among his mannequins.": "냉동실은 잠겨 있다. 양배는 마네킹들 사이에서 열쇠를 잃어버렸다고 말한다.",
  "'It was small. I saw it in the woods and just fired. Then I put it on ice. I did not know anyone would come looking.'": "'작았어. 숲에서 보고 그냥 쐈어. 그다음 얼음 속에 넣었지. 누가 찾으러 올 줄은 몰랐어.'",
  "'Why are you looking at my freezer? There is nothing in there worth naming.'": "'왜 내 냉동실을 보는 거야? 안에는 이름 붙일 만한 게 아무것도 없어.'",
  "Yang-bae's delivery marks overlap the place where he says he fired. Sung-ki's sweep is heading toward the same basin.": "양배의 배달 표식은 그가 발포했다고 말한 장소와 겹친다. 성기의 수색선도 같은 분지로 향한다.",
  "A carpenter's delivery route. It needs the official search map and an honest statement.": "목수의 배달 경로. 공식 수색 지도와 정직한 진술이 필요하다.",
  "Beneath the canvas is a child-sized green body. The shutter fixes the fact Yang-bae tried to freeze outside time.": "캔버스 천 아래에는 아이 크기의 녹색 몸이 있다. 셔터가 양배가 시간 밖에 얼려 두려 한 사실을 고정한다.",
  "Sung-ae's field card leaves no ambiguity: a single projectile entered before the body was frozen.": "성애의 현장 판정표에는 모호함이 없다. 몸이 얼기 전에 하나의 탄환이 들어갔다.",
  "Small hands. No visible weapon. Document the body before deciding what it was.": "작은 손. 보이는 무기는 없다. 무엇이었는지 결정하기 전에 몸부터 기록해야 한다.",
  "A spent hunting casing is frozen into runoff beneath the rack. The firing-pin mark is distinctive.": "받침대 아래 녹은 물에 발사된 사냥탄 탄피가 얼어붙어 있다. 공이 자국이 뚜렷하다.",
  "Meltwater runs toward the door, carrying a trace Yang-bae missed.": "녹은 물이 양배가 놓친 흔적을 싣고 문 쪽으로 흐른다.",
  "The compressor has run for days. Kali was hidden before Bamigir reached the village.": "압축기는 며칠째 돌아갔다. 칼리는 바미기르가 마을에 도착하기 전부터 숨겨져 있었다.",
  "The tag's silver-grey soil is identical. Yang-bae carried something from this trail back to his workshop.": "꼬리표의 은회색 흙과 정확히 일치한다. 양배는 이 산길에서 무언가를 작업실로 옮겼다.",
  "Unusual grey soil. Something from the workshop may connect Yang-bae to this route.": "이상한 회색 흙. 작업실의 무언가가 양배와 이 길을 연결할 수 있다.",
  "At least four anatomies crossed here: upright, hoof-like, clawed, and child-sized. This is not one beast's territory.": "최소 네 종류의 신체 구조가 이곳을 지났다. 직립형, 발굽형, 발톱형, 아이 크기. 한 짐승의 영역이 아니다.",
  "Too many overlapping impressions for the naked eye. Establish Yang-bae's path, then document them.": "맨눈으로 구분하기에는 흔적이 너무 많이 겹쳤다. 양배의 경로를 확정한 뒤 기록해야 한다.",
  "The ammunition passes down the line. A voice sounds ahead; Yang-bae fires before Sung-ki can stop him.": "탄약이 수색선을 따라 전달된다. 앞에서 목소리가 들리고, 성기가 막기 전에 양배가 발포한다.",
  "'Yang-bae fired first once already. Safeties on. We find out who followed that child before we make it happen again.'": "'양배가 이미 한 번 먼저 쐈어. 안전장치 걸어. 그 아이를 누가 따라왔는지 알아내기 전에는 같은 일을 반복하지 않는다.'",
  "The hunters still think they are pursuing one creature. Bring them evidence before the ridge closes behind them.": "사냥꾼들은 아직 하나의 생물을 쫓는다고 생각한다. 능선이 뒤를 닫기 전에 증거를 가져가야 한다.",
  "Beyond the ridge, sunlight runs across a silver structure far larger than any vehicle in Hopo.": "능선 너머에서 햇빛이 호포의 어떤 차량보다 큰 은빛 구조물을 훑는다.",
  "Something reflects beyond the ridge. The search line is not ready to approach it armed and uninformed.": "능선 너머에서 무언가 반사된다. 수색대는 무장한 채 아무것도 모르는 상태로 접근할 준비가 되지 않았다.",
  "Trees are sheared along the approach trench and the hull is folded outward. The vessel crashed; it did not land in formation.": "진입 골을 따라 나무가 잘려 있고 선체는 바깥쪽으로 접혔다. 이 선체는 추락했다. 대형을 갖춰 착륙한 것이 아니다.",
  "The silver structure is damaged from within and without. Read the terrain before calling it an invasion craft.": "은빛 구조물은 안팎으로 손상됐다. 침공선이라고 부르기 전에 지형을 읽어야 한다.",
  "Every trail print begins at the ruptured vessel. The figures in the mountain are survivors of the same crash.": "모든 흔적은 파열된 선체에서 시작한다. 산속의 형체들은 같은 추락 사고의 생존자다.",
  "Several paths leave the wreck. Compare them with the documented trail anatomies.": "잔해에서 여러 길이 뻗는다. 기록된 산길의 신체 흔적과 비교해야 한다.",
  "'This compartment fits the child in Yang-bae's freezer. They did not come to Hopo looking for us. They are looking for Kali.'": "'이 격실은 양배의 냉동실에 있던 아이와 크기가 맞아. 그들은 우리를 찾으러 호포에 온 게 아니야. 칼리를 찾고 있어.'",
  "A small restraint and an empty cradle. Evidence from the freezer could identify who is missing.": "작은 고정 장치와 빈 요람. 냉동실의 증거라면 누가 사라졌는지 확인할 수 있다.",
  "Sung-ki leads the hunters down with safeties engaged. Voices—structured, repeated, unanswered—rise from the glade.": "성기가 안전장치를 건 사냥꾼들을 이끌고 내려간다. 규칙적이고 반복되지만 답을 받지 못한 목소리가 빈터에서 올라온다.",
  "Figures wait below. Do not enter until the missing child and the first shot are connected.": "아래에서 형체들이 기다린다. 실종된 아이와 최초 발포가 연결되기 전에는 들어가면 안 된다.",
  "Ma'veyyo steps forward and speaks. Zor and Aydobor hold position. The hunters are surrounded, but the strangers do not strike first.": "마베요가 앞으로 나와 말한다. 조르와 아이도보르는 자리를 지킨다. 사냥꾼들은 포위됐지만 낯선 이들은 먼저 공격하지 않는다.",
  "A rifle answers Ma'veyyo's voice. His body changes for pursuit, and the hunt reverses in a single shot.": "마베요의 목소리에 소총이 답한다. 그의 몸이 추격을 위해 변하고 단 한 발로 사냥이 뒤집힌다.",
  "The red flare burns between both groups. Every human muzzle lowers. For one breath, nobody crosses the line.": "붉은 신호탄이 두 무리 사이에서 타오른다. 모든 인간의 총구가 내려간다. 한 번 숨 쉬는 동안 누구도 선을 넘지 않는다.",
  "Ma'veyyo recognizes Kali. The sound he makes is not a battle cry. The causal chain is finally visible: crash, missing child, human bullet, search, panic.": "마베요가 칼리를 알아본다. 그가 내는 소리는 전투의 함성이 아니다. 인과가 마침내 보인다. 추락, 실종된 아이, 인간의 탄환, 수색, 공포.",
  "Bum-seok places Yang-bae's statement beside Kali's photograph. Hopo's report begins with the shot its own hunter fired.": "범석이 양배의 진술서를 칼리의 사진 옆에 놓는다. 호포의 보고서는 마을의 사냥꾼이 쏜 한 발에서 시작한다.",
  "The royal guard watches the hunters and waits. Observation has bought seconds, not understanding.": "왕실 경호원이 사냥꾼들을 지켜보며 기다린다. 관찰은 몇 초를 벌었을 뿐 이해를 주지는 않았다.",
  "Zor shields the smaller Aydobor. Their bodies and ranks differ, but both keep looking past the hunters toward Hopo.": "조르는 더 작은 아이도보르를 감싼다. 몸과 지위는 다르지만 둘 다 사냥꾼 너머 호포를 바라본다.",
  "Sung-ki marks a withdrawal behind the flare. The hunters leave the encirclement without adding another body to the misunderstanding.": "성기가 신호탄 뒤로 철수로를 표시한다. 사냥꾼들은 오해에 또 하나의 시신을 더하지 않고 포위망을 빠져나간다.",
  "The withdrawal line crosses open ground. It needs a ceasefire signal and a complete cause report.": "철수로는 노출된 지면을 가로지른다. 정전 신호와 완성된 인과 보고서가 필요하다.",
  "HOPO PORT · AFTER THE FIRST ATTACK · 13:42": "호포항 · 첫 습격 이후 · 13:42",
  "'Bamigir is down. That does not mean it came alone.'": "'바미기르가 쓰러졌어. 그렇다고 혼자 왔다는 뜻은 아니야.'",
  "'The tracks go into the mountain. We move before they circle back.'": "'흔적은 산으로 이어져. 놈들이 돌아오기 전에 움직인다.'",
  "Establish cause before arming the search line. A second first shot ends the investigation.": "수색대를 무장시키기 전에 원인을 규명하십시오. 두 번째 최초 발포는 수사를 끝냅니다.",
  "You wait. Sung-ki's search line climbs while the mountain answers with unfamiliar voices.": "기다린다. 성기의 수색선이 오르는 동안 산은 낯선 목소리로 답한다.",
  "Causality Record · Mountain Search": "인과 기록 · 산악 수색",
  "Preceding event": "선행 사건",
  "Kali killed by a human projectile before the village attack": "마을 습격 전에 칼리가 인간의 탄환에 맞아 사망",
  "Search party": "수색 대상",
  "multiple anatomies; one crashed vessel": "여러 신체 구조; 하나의 추락 선체",
  "Missing subject": "실종 대상",
  "child-sized compartment linked to Kali": "아이 크기 격실이 칼리와 연결됨",
  "Contact behavior": "접촉 행동",
  "royal survivors spoke and held position before human fire": "왕실 생존자들은 인간의 발포 전까지 말하며 자리를 지킴",
  "Yang-bae statement · fired without warning; concealed the body": "양배 진술 · 경고 없이 발포; 시신 은닉",
  "causality note · humans were victims and unknowing aggressors": "인과 메모 · 인간은 피해자이자 자신도 모르는 가해자였음",

  // Shared state-engine messages
  "Nothing happens.": "아무 일도 일어나지 않는다.",
  "That doesn't fit here.": "여기에는 사용할 수 없다.",
  "That way is closed.": "그쪽 길은 막혀 있다.",
};

export const GAME_ROLES_KO: Record<string, string> = {
  SYSTEM: "시스템",
  RADIO: "무전",
  "SUNG-GI": "성기",
  "SUNG-KI": "성기",
  "SUNG-AE": "성애",
  "BUM-SEOK": "범석",
  "YANG-BAE": "양배",
  TUTORIAL: "안내",
  OMEGA: "오메가",
};
